// <auto-generated />
namespace Lpp.Dns.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class OrganizationsEtc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrganizationsEtc));
        
        string IMigrationMetadata.Id
        {
            get { return "201312041146586_OrganizationsEtc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
