// <auto-generated />
namespace Lpp.Dns.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateWorkflowRoles_AddDataCheckerWorkflowRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateWorkflowRoles_AddDataCheckerWorkflowRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201509221757232_UpdateWorkflowRoles_AddDataCheckerWorkflowRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
