//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theme.Default {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Theme {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Theme() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Theme.Default.Theme", typeof(Theme).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2015 PopMedNet, All Rights Reserved.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The FDA Sentinel applications are funded under FDA&apos;s Sentinel contract (Contract No. HHSF223200910006I). The Distributed Query Tool system is based on the AHRQ-supported Distributed Research Network project, funded as part of the Developing Evidence to Inform Decisions about Effectiveness (DEcIDE) program (Contract No. 290-05-0033).&lt;/p&gt;.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/pmn-logo.png.
        /// </summary>
        internal static string LogoImage {
            get {
                return ResourceManager.GetString("LogoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-sm-12 form-group&quot;&gt;&lt;b&gt;Mini-Sentinel Operations Center Contact:&lt;/b&gt;&amp;nbsp;&lt;a href=&quot;mailto:support@popmednet.org&quot;&gt;support@popmednet.org&lt;/a&gt;&lt;/div&gt;                
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-sm-12 form-group&quot;&gt;&lt;b&gt;Lincoln Peak Partners Contact:&lt;/b&gt;&amp;nbsp;&lt;a href=&quot;mailto:support@lincolnpeak.com&quot;&gt;support@lincolnpeak.com&lt;/a&gt;&lt;/div&gt;
        ///            &lt;/div&gt;.
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;SystemUserConfirmationContent&quot; style=&quot;width: 800px&quot;&gt;
        ///&lt;p&gt;You are accessing a U.S. Government information system, which includes (1) this computer, (2) this computer network, (3) all computers connected to this network, and (4) all devices and storage media attached to this network or to a computer on this network.&lt;/p&gt;
        ///&lt;p&gt;This information system is provided for U.S. Government-authorized use only.  Unauthorized or improper use of this system may result in disciplinary action, as well as civil and c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemUserConfirmationContent {
            get {
                return ResourceManager.GetString("SystemUserConfirmationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Required.
        /// </summary>
        internal static string SystemUserConfirmationTitle {
            get {
                return ResourceManager.GetString("SystemUserConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You are accessing a U.S. government information system. Your use of this system indicates consent to monitoring and recording. Usage of this system may be monitored, recorded, and subject to audit. Unauthorized use of this system is prohibited and subject to criminal and civil penalties.&lt;/p&gt;.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed Research Network Technologies for Population Medicine.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
