INSERT INTO [I2B2_PMN_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CHAR]) VALUES ('white','White')
INSERT INTO [I2B2_PMN_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CHAR]) VALUES ('black','Black or African American')
INSERT INTO [I2B2_PMN_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CHAR]) VALUES ('asian','Asian')
INSERT INTO [I2B2_PMN_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CHAR]) VALUES ('hispanic','Hispanic')
INSERT INTO [I2B2_PMN_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CHAR]) VALUES ('indian','American Indian or Alaska Native')
INSERT INTO [I2B2_PMN_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CHAR]) VALUES ('unknown','Unknown')
GO


