USE [i2b2_data]
GO

/****** Object:  Table [dbo].[ICD9_CODE_LOOKUP]    Script Date: 08/29/2013 10:43:56 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ICD9_CODE_LOOKUP]') AND type in (N'U'))
DROP TABLE [dbo].[ICD9_CODE_LOOKUP]
GO

USE [i2b2_data]
GO

/****** Object:  Table [dbo].[ICD9_CODE_LOOKUP]    Script Date: 08/29/2013 10:43:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ICD9_CODE_LOOKUP](
	[CONCEPT_CD] [varchar](50) NOT NULL,
	[CODE_3DIG] [varchar](50) NULL,
	[NAME_3DIG] [varchar](500) NULL,
	[CODE_4DIG] [varchar](50) NULL,
	[NAME_4DIG] [varchar](500) NULL,
	[CODE_5DIG] [varchar](50) NULL,
	[NAME_5DIG] [varchar](500) NULL,
 CONSTRAINT [PK_ICD9_CODE_LOOKUP] PRIMARY KEY CLUSTERED 
(
	[CONCEPT_CD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


