INSERT INTO [PMN_I2B2_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CODE]) VALUES ('unknown',0)
INSERT INTO [PMN_I2B2_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CODE]) VALUES ('indian',1)
INSERT INTO [PMN_I2B2_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CODE]) VALUES ('asian',2)
INSERT INTO [PMN_I2B2_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CODE]) VALUES ('black',3)
INSERT INTO [PMN_I2B2_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CODE]) VALUES ('pacific',4)
INSERT INTO [PMN_I2B2_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CODE]) VALUES ('white',5)
INSERT INTO [PMN_I2B2_RACE_CODE_LOOKUP] ([RACE_CD],[RACE_CODE]) VALUES ('hispanic',5)
GO


