# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


name: tags_2022.2$(rev:.r)
trigger: none
pr: none

variables:
- template: Variables.yml

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget Tools'

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.1.x'
  inputs:
    version: 3.1.x

- task: NuGetCommand@2
  displayName: Restore Nuget for DMCS
  inputs:
    restoreSolution: './DMCS/PopMedNet.DMCS.sln'

- task: NodeTool@0
  displayName: 'Use Node 14.x'
  inputs:
    versionSpec: 14.x
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: ./DMCS/PopMedNet.DMCS
    verbose: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build for DMCS'
  inputs:
    projects: './DMCS/PopMedNet.DMCS.sln'

- script: |
   npx webpack --config webpack.config.production.js
  workingDirectory: ./DMCS/PopMedNet.DMCS
  displayName: 'Command Line Script'

- task: VSBuild@1
  displayName: 'Build solution PopMedNet.DMCS.sln'
  inputs:
    solution: ./DMCS/PopMedNet.DMCS.sln
    msbuildArgs: '/p:WebPublishMethod=FileSystem /p:DeployOnBuild=true /p:DeployTarget=WebPublish /p:publishUrl=$(Build.ArtifactStagingDirectory)\Web /p:DeleteExistingFiles=True'

- task: Artifacts-Compress@2
  inputs:
    source: '$(Build.ArtifactStagingDirectory)\Web'
    dest: '$(Build.ArtifactStagingDirectory)'
    compressionLevel: 'Fastest'
    multiplePackages: false
    cleanDest: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


