#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.HealthCare.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ObservationPeriodPlugin.cshtml")]
    public partial class ObservationPeriodPlugin : System.Web.Mvc.WebViewPage<Lpp.Dns.HealthCare.Models.ObservationPeriodPluginModel>
    {
        public ObservationPeriodPlugin()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\ObservationPeriodPlugin.cshtml"
  
    string fldStartPeriod = string.Format("{0}_{1}", Model.ParentContext, "StartPeriod");
    string fldEndPeriod = string.Format("{0}_{1}", Model.ParentContext, "EndPeriod");    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).ready(function () {\r\n        $(\'#");

            
            #line 10 "..\..\Views\ObservationPeriodPlugin.cshtml"
       Write(fldStartPeriod);

            
            #line default
            #line hidden
WriteLiteral(", #");

            
            #line 10 "..\..\Views\ObservationPeriodPlugin.cshtml"
                         Write(fldEndPeriod);

            
            #line default
            #line hidden
WriteLiteral("\')\r\n        .datepicker({\r\n            changeMonth: true,\r\n            changeYear" +
": true,\r\n            defaultDate: +0,\r\n            maxDate: \'12/31/2299\',\r\n     " +
"       minDate: \'01/01/1900\',\r\n            showButtonPanel: true\r\n        })\r\n  " +
"      .change(function () {\r\n            if (!$(this).isValidDate($(this).val())" +
") {\r\n                alert(\'Please Enter Valid Date in MM/DD/YYYY Format\');\r\n   " +
"             return false;\r\n            }\r\n        })\r\n        .keyup(function (" +
"e) {\r\n            $(this).datepicker(\"hide\");\r\n            if (e.keyCode != 8) {" +
"\r\n                if ($(this).val().length == 2) {\r\n                    $(this)." +
"val($(this).val() + \"/\");\r\n                }\r\n\r\n                if ($(this).val(" +
").length == 5) {\r\n                    $(this).val($(this).val() + \"/\");\r\n       " +
"         }\r\n            }\r\n\r\n            return false;\r\n        })\r\n        .key" +
"press(function (e) {\r\n            var key;\r\n\r\n            if (window.event)\r\n   " +
"             key = window.event.keyCode;     //IE\r\n            else\r\n           " +
"     key = e.which;                  //firefox\r\n\r\n            if (key == 47) {\r\n" +
"                return false;\r\n            }\r\n        });\r\n\r\n        $(function " +
"() {\r\n            $.fn.isValidDate = function jQuery$isValidDate(date) {\r\n      " +
"          var reDate = /^(((((((0[13578])|(1[02]))[\\/]((0[1-9])|([12]\\d)|(3[01])" +
"))|(((0[469])|(11))[\\/]((0[1-9])|([12]\\d)|(30)))|((02)[\\/]((0[1-9])|(1\\d)|(2[0-8" +
"]))))[\\/](((19)|(20)|(21)|(22))([0-9][0-9]))))|((02)[\\/](29)[\\/](((19)|(20)|(21)" +
"|(22))(([02468][048])|([13579][26])))))$/;\r\n                return reDate.test(d" +
"ate);\r\n            };\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" class=\"ui-groupbox\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui-groupbox-header\"");

WriteLiteral(">\r\n        <span>Observation Period Range<img");

WriteLiteral(" src=\"/Content/img/icons/help16.gif\"");

WriteLiteral(" class=\"helptip\"");

WriteLiteral(" title=\"Dates may differ by network and are based on encounter dates.\"");

WriteLiteral(" /></span>\r\n    </div>\r\n    <table>\r\n        <tr>\r\n            <td>\r\n            " +
"    <div");

WriteLiteral(" class=\"ui-form\"");

WriteLiteral(">\r\n                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 70 "..\..\Views\ObservationPeriodPlugin.cshtml"
                   Write(Html.LabelFor(opm => opm.StartPeriod));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <label");

WriteLiteral(" style=\"color: red; font-size: x-small;\"");

WriteLiteral(">\r\n                            (MM/DD/YYYY)</label>\r\n                    </div>\r\n" +
"                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 75 "..\..\Views\ObservationPeriodPlugin.cshtml"
                   Write(Html.TextBox(fldStartPeriod, Model.StartPeriod.ToString("MM/dd/yyyy"), new { id = fldStartPeriod, style = "width: 80px;", maxlength = 10 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </td>\r\n        " +
"    <td>\r\n                <div");

WriteLiteral(" class=\"ui-form\"");

WriteLiteral(">\r\n                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 82 "..\..\Views\ObservationPeriodPlugin.cshtml"
                   Write(Html.LabelFor(opm => opm.EndPeriod));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <label");

WriteLiteral(" style=\"color: red; font-size: x-small;\"");

WriteLiteral(">(MM/DD/YYYY)</label>\r\n                    </div>\r\n                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 86 "..\..\Views\ObservationPeriodPlugin.cshtml"
                   Write(Html.TextBox(fldEndPeriod, Model.EndPeriod.ToString("MM/dd/yyyy"), new { id = fldEndPeriod, style = "width: 80px;", maxlength = 10 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </td>\r\n        " +
"</tr>\r\n    </table>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
