// <auto-generated />
namespace Lpp.Dns.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class SsoEndpointSchemaModPostUrlMaxLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SsoEndpointSchemaModPostUrlMaxLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201310251211117_SsoEndpointSchemaModPostUrlMaxLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
