// <auto-generated />
namespace Lpp.Dns.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddSaveToWFActivities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSaveToWFActivities));
        
        string IMigrationMetadata.Id
        {
            get { return "201410211216312_AddSaveToWFActivities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
