// <auto-generated />
namespace Lpp.Dns.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FixFKOnTemplatesToRequestTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixFKOnTemplatesToRequestTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201410011742420_FixFKOnTemplatesToRequestTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
