#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.General.Metadata.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns.General.CriteriaGroup;
    using Lpp.Dns.General.CriteriaGroup.Models;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    using Lpp.Utilities.Legacy;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DisplayRegSearchResponse.cshtml")]
    public partial class DisplayRegSearchResponse : System.Web.Mvc.WebViewPage<string>
    {
        public DisplayRegSearchResponse()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\DisplayRegSearchResponse.cshtml"
   
    this.Stylesheet("MeataDataSearch.css");    

            
            #line default
            #line hidden
WriteLiteral(@"

<style>
    span.form-control {
        background-color: white;
        white-space: nowrap;
        width: 100%;
        border: solid 1px black;
        padding: 3px;
        display: block;
        min-height: 1.2em;
    }
    table.form-control {
        background-color: white;
        border: solid 1px black;
        padding: 3px;
        display: block;
        min-height: 1.2em;
    }

    table label {
        display: block;
        white-space: nowrap;
    }


    table.Grid tr.spacer {
        border-top: 0px; 
    }

    td.spacer {
        background-color: white;
        height: 5px;
        font-size: 4px;
    }
</style>

<div");

WriteLiteral(" class=\"ui-groupbox\"");

WriteLiteral(" id=\"registryResults\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui-groupbox-header\"");

WriteLiteral("><span>Registries</span></div>\r\n\r\n    <table");

WriteLiteral(" class=\"table table-striped table-bordered\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"width: 30px;\"");

WriteLiteral(">&nbsp;</th>\r\n                <th>Name</th>\r\n                <th>Type</th>\r\n     " +
"       </tr>\r\n        </thead>\r\n        <tbody");

WriteLiteral(" data-bind=\"foreach: Results\"");

WriteLiteral(">\r\n            <tr>\r\n                <td");

WriteLiteral(" style=\"white-space: nowrap;\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-bind=\"text: Expanded() ? \'[-]\' : \'[+]\', click: ExpandCollapse\"");

WriteLiteral("></a></td>\r\n                <td><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-bind=\"text: Name, attr: { href: \'/registries/details?ID=\' + ID() }\"");

WriteLiteral("></a></td>\r\n                <td");

WriteLiteral(" data-bind=\"text: RegistryType\"");

WriteLiteral("></td>\r\n            </tr>\r\n            <tr");

WriteLiteral(" data-bind=\"visible: Expanded\"");

WriteLiteral(" style=\"border-top: 0;\"");

WriteLiteral(">\r\n                <td");

WriteLiteral(" style=\"width: 30px; background-color: white; border-top: 1px solid #A2A2A0\"");

WriteLiteral(">&nbsp;</td>\r\n                <td");

WriteLiteral(" colspan=\"7\"");

WriteLiteral(" style=\"border-left: 1px solid #A2A2A0\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(">\r\n                        <tr>\r\n                            <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"txtDescription\"");

WriteLiteral(">Description</label>\r\n                                <input");

WriteLiteral(" id=\"txtDescription\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: Description\"");

WriteLiteral("/>\r\n                            </td>\r\n                        </tr>\r\n           " +
"             <tr>\r\n                            <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"txtRoPRURL\"");

WriteLiteral(">RoPR URL</label>\r\n                                <input disabled");

WriteLiteral(" id=\"txtRoPRURL\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: RoPRURL\"");

WriteLiteral("/>\r\n                            </td>\r\n                        </tr>\r\n\r\n         " +
"               <tr>\r\n                            <td");

WriteLiteral(" style=\"width: 30%; vertical-align:text-top\"");

WriteLiteral(" class=\"well\"");

WriteLiteral(">\r\n                                <label>Classification</label>\r\n               " +
"                 <table");

WriteLiteral(" style=\"vertical-align:text-top; padding-top: 10px;\"");

WriteLiteral(">\r\n                                    <tbody");

WriteLiteral(" data-bind=\"foreach: Classifications\"");

WriteLiteral(">\r\n                                        <tr>\r\n                                " +
"            <td");

WriteLiteral(" data-bind=\"text: $data\"");

WriteLiteral("></td>\r\n                                        </tr>\r\n                          " +
"          </tbody>\r\n                                </table>\r\n                  " +
"          </td>\r\n                            <td");

WriteLiteral(" style=\"width: 5%;\"");

WriteLiteral("></td>\r\n                            <td");

WriteLiteral(" style=\"width: 30%; vertical-align:text-top\"");

WriteLiteral(" class=\"well\"");

WriteLiteral(">\r\n                                <label>Conditions Of Interest</label>\r\n       " +
"                         <table");

WriteLiteral(" style=\"vertical-align:text-top; padding-top: 10px;\"");

WriteLiteral(">\r\n                                    <tbody");

WriteLiteral(" data-bind=\"foreach: ConditionsOfInterest\"");

WriteLiteral(">\r\n                                        <tr>\r\n                                " +
"            <td");

WriteLiteral(" data-bind=\"text: $data\"");

WriteLiteral("></td>\r\n                                        </tr>\r\n                          " +
"          </tbody>\r\n                                </table>\r\n                  " +
"          </td>\r\n                            <td");

WriteLiteral(" style=\"width: 5%;\"");

WriteLiteral("></td>\r\n                            <td");

WriteLiteral(" style=\"width: 30%; vertical-align:text-top\"");

WriteLiteral(" class=\"well\"");

WriteLiteral(">\r\n                                <label>Purposes</label>\r\n                     " +
"           <table");

WriteLiteral(" style=\"vertical-align:text-top; padding-top: 10px;\"");

WriteLiteral(">\r\n                                    <tbody");

WriteLiteral(" data-bind=\"foreach: Purposes\"");

WriteLiteral(">\r\n                                        <tr>\r\n                                " +
"            <td");

WriteLiteral(" data-bind=\"text: $data\"");

WriteLiteral(@"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>

                        <tr>
                            <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"txtOrganizationsCount\"");

WriteLiteral(">Organizations with this registry:</label>\r\n                                <inpu" +
"t disabled");

WriteLiteral(" id=\"txtOrganizationsCount\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: OrganizationCount\"");

WriteLiteral(" style=\"width:20px\"");

WriteLiteral(" />\r\n                            </td>\r\n                        </tr>\r\n          " +
"              <tr>\r\n                            <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"txtDataMartsCount\"");

WriteLiteral(">DataMarts with this registry:</label>\r\n                                <input di" +
"sabled");

WriteLiteral(" id=\"txtDataMartsCount\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: DataMartCount\"");

WriteLiteral(" style=\"width:20px\"");

WriteLiteral(" />\r\n                            </td>\r\n                        </tr>\r\n          " +
"          </table>\r\n                </td>\r\n            </tr>\r\n            <tr");

WriteLiteral(" data-bind=\"visible: Expanded\"");

WriteLiteral(" class=\"spacer\"");

WriteLiteral(">\r\n                <td");

WriteLiteral(" class=\"spacer\"");

WriteLiteral(" style=\"border-top: 0;\"");

WriteLiteral(">&nbsp;</td>\r\n                <td");

WriteLiteral(" colspan=\"7\"");

WriteLiteral(" class=\"spacer\"");

WriteLiteral(" style=\"border-top: 1px solid #A2A2A0\"");

WriteLiteral(">&nbsp;</td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n </div>\r\n\r\n<scri" +
"pt");

WriteAttribute("src", Tuple.Create(" src=\"", 5817), Tuple.Create("\"", 5867)
            
            #line 133 "..\..\Views\DisplayRegSearchResponse.cshtml"
, Tuple.Create(Tuple.Create("", 5823), Tuple.Create<System.Object, System.Int32>(this.Resource("DisplayRegistryResponse.js")
            
            #line default
            #line hidden
, 5823), false)
);

WriteLiteral("></script>\r\n<script>\r\n    //Load the data here from the json that is serialized i" +
"n from the model.\r\n    var data = ");

            
            #line 136 "..\..\Views\DisplayRegSearchResponse.cshtml"
          Write(Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model == null ? "{}" : Model)));

            
            #line default
            #line hidden
WriteLiteral(";\r\n    data = JSON.parse(data);\r\n    MetaData.DisplayRegistryResponse.init(data |" +
"| [], $(\"#registryResults\"));\r\n</script>");

        }
    }
}
#pragma warning restore 1591
