#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.General.CriteriaGroup.Views.CriteriaGroup.Terms
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns.General.CriteriaGroup;
    using Lpp.Dns.General.CriteriaGroup.Models;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    using Lpp.Utilities.Legacy;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CriteriaGroup/Terms/Dummy.cshtml")]
    public partial class Dummy : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Dummy()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!-- Template for creating new terms. -->\r\n<div");

WriteLiteral(" class=\"DummyTerm Term ui-groupbox\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" name=\"TermName\"");

WriteLiteral(" value=");

WriteLiteral(" \"Dummy\" hidden=\"hidden\" style=\"display:none\" />\r\n    <div");

WriteLiteral(" class=\"ui-groupbox-header\"");

WriteLiteral(">\r\n        <span>Dummy</span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"Dummy\"");

WriteLiteral(">\r\n        Dummy\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
