#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.Portal.Views.SharedFolders
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns;
    using Lpp.Dns.Data;
    using Lpp.Dns.Portal;
    using Lpp.Dns.Portal.Controllers;
    using Lpp.Dns.Portal.Models;
    using Lpp.Dns.Portal.Views;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SharedFolders/TreeNode.cshtml")]
    public partial class TreeNode : System.Web.Mvc.WebViewPage<RequestSharedFolder>
    {
        public TreeNode()
        {
        }
        public override void Execute()
        {
WriteLiteral("<img");

WriteAttribute("src", Tuple.Create(" src=\"", 33), Tuple.Create("\"", 87)
            
            #line 2 "..\..\Views\SharedFolders\TreeNode.cshtml"
, Tuple.Create(Tuple.Create("", 39), Tuple.Create<System.Object, System.Int32>(this.Resource( "img/icons/request_folder.ico" )
            
            #line default
            #line hidden
, 39), false)
);

WriteLiteral(" height=\"24\"");

WriteLiteral(" width=\"24\"");

WriteLiteral(" />\r\n<a");

WriteLiteral(" data-folderid=\"");

            
            #line 3 "..\..\Views\SharedFolders\TreeNode.cshtml"
             Write(Model.ID);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"SharedFolder\"");

WriteAttribute("href", Tuple.Create(" href=\"", 165), Tuple.Create("\"", 266)
            
            #line 3 "..\..\Views\SharedFolders\TreeNode.cshtml"
, Tuple.Create(Tuple.Create("", 172), Tuple.Create<System.Object, System.Int32>(Url.Action( (SharedFolderController c) => c.Contents( Model.ID, new RequestListGetModel() ) )
            
            #line default
            #line hidden
, 172), false)
);

WriteLiteral(">");

            
            #line 3 "..\..\Views\SharedFolders\TreeNode.cshtml"
                                                                                                                                                   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>");

        }
    }
}
#pragma warning restore 1591
