//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.QueryComposer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelTermResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelTermResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lpp.QueryComposer.ModelTermResources", typeof(ModelTermResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool for describing a series of events..
        /// </summary>
        public static string AbsoluteTime_Description {
            get {
                return ResourceManager.GetString("AbsoluteTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute Time.
        /// </summary>
        public static string AbsoluteTime_Name {
            get {
                return ResourceManager.GetString("AbsoluteTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A range of ages for the patient subject of the encounter..
        /// </summary>
        public static string AgeRange_Description {
            get {
                return ResourceManager.GetString("AgeRange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Range.
        /// </summary>
        public static string AgeRange_Name {
            get {
                return ResourceManager.GetString("AgeRange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diastolic and systolic blood pressure..
        /// </summary>
        public static string BloodPressure_Description {
            get {
                return ResourceManager.GetString("BloodPressure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        public static string BloodPressure_Name {
            get {
                return ResourceManager.GetString("BloodPressure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body mass index (BMI) of the patient subject..
        /// </summary>
        public static string BMI_Description {
            get {
                return ResourceManager.GetString("BMI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Mass Index (BMI).
        /// </summary>
        public static string BMI_Name {
            get {
                return ResourceManager.GetString("BMI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you able to request, or review, charts for this person.
        /// </summary>
        public static string ChartAvailable_Description {
            get {
                return ResourceManager.GetString("ChartAvailable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Available.
        /// </summary>
        public static string ChartAvailable_Name {
            get {
                return ResourceManager.GetString("ChartAvailable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of code metric types.
        /// </summary>
        public static string CodeMetric_Description {
            get {
                return ResourceManager.GetString("CodeMetric_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Metric Type.
        /// </summary>
        public static string CodeMetric_Name {
            get {
                return ResourceManager.GetString("CodeMetric_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A common term for diagnosis codes allowing the specific code set and values to be queried..
        /// </summary>
        public static string CombinedDiagnosisCodes_Description {
            get {
                return ResourceManager.GetString("CombinedDiagnosisCodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string CombinedDiagnosisCodes_Name {
            get {
                return ResourceManager.GetString("CombinedDiagnosisCodes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general condition reported during the encounter..
        /// </summary>
        public static string Conditions_Description {
            get {
                return ResourceManager.GetString("Conditions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions_Name {
            get {
                return ResourceManager.GetString("Conditions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of Coverages for patient encounters..
        /// </summary>
        public static string Coverage_Description {
            get {
                return ResourceManager.GetString("Coverage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        public static string Coverage_Name {
            get {
                return ResourceManager.GetString("Coverage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of Output Criteria.
        /// </summary>
        public static string Criteria_Description {
            get {
                return ResourceManager.GetString("Criteria_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Criteria.
        /// </summary>
        public static string Criteria_Name {
            get {
                return ResourceManager.GetString("Criteria_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient&apos;s date of birth..
        /// </summary>
        public static string DateOfBirth_Description {
            get {
                return ResourceManager.GetString("DateOfBirth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth_Name {
            get {
                return ResourceManager.GetString("DateOfBirth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Distribution Term for Data Checker.
        /// </summary>
        public static string DC_AgeDistribution_Description {
            get {
                return ResourceManager.GetString("DC_AgeDistribution_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Distribution.
        /// </summary>
        public static string DC_AgeDistribution_Name {
            get {
                return ResourceManager.GetString("DC_AgeDistribution_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Partners Term for Data Checker.
        /// </summary>
        public static string DC_DataPartners_Description {
            get {
                return ResourceManager.GetString("DC_DataPartners_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Partners.
        /// </summary>
        public static string DC_DataPartners_Name {
            get {
                return ResourceManager.GetString("DC_DataPartners_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Codes Term for DataChecker.
        /// </summary>
        public static string DC_DiagnosisCodes_Description {
            get {
                return ResourceManager.GetString("DC_DiagnosisCodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Codes.
        /// </summary>
        public static string DC_DiagnosisCodes_Name {
            get {
                return ResourceManager.GetString("DC_DiagnosisCodes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis PDX Term for DataChecker.
        /// </summary>
        public static string DC_DiagnosisPDX_Description {
            get {
                return ResourceManager.GetString("DC_DiagnosisPDX_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis PDX.
        /// </summary>
        public static string DC_DiagnosisPDX_Name {
            get {
                return ResourceManager.GetString("DC_DiagnosisPDX_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispensing RX Amount Term for DataChecker.
        /// </summary>
        public static string DC_DispensingRXAmount_Description {
            get {
                return ResourceManager.GetString("DC_DispensingRXAmount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispensing RX Amount.
        /// </summary>
        public static string DC_DispensingRXAmount_Name {
            get {
                return ResourceManager.GetString("DC_DispensingRXAmount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispensing RX Supply Term for DataChecker.
        /// </summary>
        public static string DC_DispensisngRXSupply_Description {
            get {
                return ResourceManager.GetString("DC_DispensisngRXSupply_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispensing RX Supply.
        /// </summary>
        public static string DC_DispensisngRXSupply_Name {
            get {
                return ResourceManager.GetString("DC_DispensisngRXSupply_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter Term for DataChecker.
        /// </summary>
        public static string DC_Encounter_Description {
            get {
                return ResourceManager.GetString("DC_Encounter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter.
        /// </summary>
        public static string DC_Encounter_Name {
            get {
                return ResourceManager.GetString("DC_Encounter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity Term for DataChecker.
        /// </summary>
        public static string DC_Ethnicity_Description {
            get {
                return ResourceManager.GetString("DC_Ethnicity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity.
        /// </summary>
        public static string DC_Ethnicity_Name {
            get {
                return ResourceManager.GetString("DC_Ethnicity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Distribution term for Data Checker..
        /// </summary>
        public static string DC_HeightDistribution_Description {
            get {
                return ResourceManager.GetString("DC_HeightDistribution_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Distribution.
        /// </summary>
        public static string DC_HeightDistribution_Name {
            get {
                return ResourceManager.GetString("DC_HeightDistribution_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Completeness Term for DataChecker.
        /// </summary>
        public static string DC_MetadataCompleteness_Description {
            get {
                return ResourceManager.GetString("DC_MetadataCompleteness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Completeness.
        /// </summary>
        public static string DC_MetadataCompleteness_Name {
            get {
                return ResourceManager.GetString("DC_MetadataCompleteness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDC Codes Term for DataChecker.
        /// </summary>
        public static string DC_NDCCodes_Description {
            get {
                return ResourceManager.GetString("DC_NDCCodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDC Codes.
        /// </summary>
        public static string DC_NDCCodes_Name {
            get {
                return ResourceManager.GetString("DC_NDCCodes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Codes Term for DataChecker.
        /// </summary>
        public static string DC_ProcedureCodes_Description {
            get {
                return ResourceManager.GetString("DC_ProcedureCodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Codes.
        /// </summary>
        public static string DC_ProcedureCodes_Name {
            get {
                return ResourceManager.GetString("DC_ProcedureCodes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported race of the patient subject..
        /// </summary>
        public static string DC_Race_Description {
            get {
                return ResourceManager.GetString("DC_Race_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string DC_Race_Name {
            get {
                return ResourceManager.GetString("DC_Race_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex Distribution Term for DataChecker.
        /// </summary>
        public static string DC_SexDistribution_Description {
            get {
                return ResourceManager.GetString("DC_SexDistribution_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex Distribution.
        /// </summary>
        public static string DC_SexDistribution_Name {
            get {
                return ResourceManager.GetString("DC_SexDistribution_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Distribution Term for DataChecker.
        /// </summary>
        public static string DC_WeightDistribution_Description {
            get {
                return ResourceManager.GetString("DC_WeightDistribution_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Distribution.
        /// </summary>
        public static string DC_WeightDistribution_Name {
            get {
                return ResourceManager.GetString("DC_WeightDistribution_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of Metic types.
        /// </summary>
        public static string DispensingMetric_Description {
            get {
                return ResourceManager.GetString("DispensingMetric_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Types.
        /// </summary>
        public static string DispensingMetric_Name {
            get {
                return ResourceManager.GetString("DispensingMetric_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A classification system that identifies the products that the patient received..
        /// </summary>
        public static string DRG_Description {
            get {
                return ResourceManager.GetString("DRG_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis-Related Group.
        /// </summary>
        public static string DRG_Name {
            get {
                return ResourceManager.GetString("DRG_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reported Drug Class.
        /// </summary>
        public static string DrugClass_Description {
            get {
                return ResourceManager.GetString("DrugClass_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Class.
        /// </summary>
        public static string DrugClass_Name {
            get {
                return ResourceManager.GetString("DrugClass_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reported Drug Name.
        /// </summary>
        public static string DrugName_Description {
            get {
                return ResourceManager.GetString("DrugName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Name.
        /// </summary>
        public static string DrugName_Name {
            get {
                return ResourceManager.GetString("DrugName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter Period Dates.
        /// </summary>
        public static string EncounterPeriod_Description {
            get {
                return ResourceManager.GetString("EncounterPeriod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter Period.
        /// </summary>
        public static string EncounterPeriod_Name {
            get {
                return ResourceManager.GetString("EncounterPeriod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter Types.
        /// </summary>
        public static string EncounterTypes_Description {
            get {
                return ResourceManager.GetString("EncounterTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string EncounterTypes_Name {
            get {
                return ResourceManager.GetString("EncounterTypes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A common term for diagnosis codes allowing the specific code set and values to be queried..
        /// </summary>
        public static string ESPDiagnosisCodes_Description {
            get {
                return ResourceManager.GetString("ESPDiagnosisCodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP Diagnosis.
        /// </summary>
        public static string ESPDiagnosisCodes_Name {
            get {
                return ResourceManager.GetString("ESPDiagnosisCodes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ethnicity of the patient subject..
        /// </summary>
        public static string Ethnicity_Description {
            get {
                return ResourceManager.GetString("Ethnicity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race-Ethnicity.
        /// </summary>
        public static string Ethnicity_Name {
            get {
                return ResourceManager.GetString("Ethnicity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility(s) visited by the patient..
        /// </summary>
        public static string Facility_Description {
            get {
                return ResourceManager.GetString("Facility_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        public static string Facility_Name {
            get {
                return ResourceManager.GetString("Facility_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files for a file distribution request..
        /// </summary>
        public static string FileUpload_Description {
            get {
                return ResourceManager.GetString("FileUpload_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload.
        /// </summary>
        public static string FileUpload_Name {
            get {
                return ResourceManager.GetString("FileUpload_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported HCPCS codes of the encounter..
        /// </summary>
        public static string HCPCSCodes_Description {
            get {
                return ResourceManager.GetString("HCPCSCodes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCPCS Codes.
        /// </summary>
        public static string HCPCSCodes_Name {
            get {
                return ResourceManager.GetString("HCPCSCodes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the patient..
        /// </summary>
        public static string Height_Description {
            get {
                return ResourceManager.GetString("Height_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height_Name {
            get {
                return ResourceManager.GetString("Height_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hispanic.
        /// </summary>
        public static string Hispanic_Description {
            get {
                return ResourceManager.GetString("Hispanic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hispanic.
        /// </summary>
        public static string Hispanic_Name {
            get {
                return ResourceManager.GetString("Hispanic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-10 Diagnosis codes (3 digit) of the encounter..
        /// </summary>
        public static string ICD10Diagnosis3Digit_Description {
            get {
                return ResourceManager.GetString("ICD10Diagnosis3Digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-10 Diagnosis Codes (3 digit).
        /// </summary>
        public static string ICD10Diagnosis3Digit_Name {
            get {
                return ResourceManager.GetString("ICD10Diagnosis3Digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-10 Diagnosis codes (4 digit) of the encounter..
        /// </summary>
        public static string ICD10Diagnosis4Digit_Description {
            get {
                return ResourceManager.GetString("ICD10Diagnosis4Digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-10 Diagnosis Codes (4 digit).
        /// </summary>
        public static string ICD10Diagnosis4Digit_Name {
            get {
                return ResourceManager.GetString("ICD10Diagnosis4Digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-10 Diagnosis codes (5 digit) of the encounter..
        /// </summary>
        public static string ICD10Diagnosis5Digit_Description {
            get {
                return ResourceManager.GetString("ICD10Diagnosis5Digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-10 Diagnosis Codes (5 digit).
        /// </summary>
        public static string ICD10Diagnosis5Digit_Name {
            get {
                return ResourceManager.GetString("ICD10Diagnosis5Digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-10 Procedure codes (3 Digit) of the encounter..
        /// </summary>
        public static string ICD10Procedure3Digit_Description {
            get {
                return ResourceManager.GetString("ICD10Procedure3Digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-10 Procedure Codes (3 Digit).
        /// </summary>
        public static string ICD10Procedure3Digit_Name {
            get {
                return ResourceManager.GetString("ICD10Procedure3Digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-10 Procedure codes (4 Digit) of the encounter..
        /// </summary>
        public static string ICD10Procedure4Digit_Description {
            get {
                return ResourceManager.GetString("ICD10Procedure4Digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ICD-10 Procedure Code (4 Digit).
        /// </summary>
        public static string ICD10Procedure4Digit_Name {
            get {
                return ResourceManager.GetString("ICD10Procedure4Digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-9 Diagnosis codes (3 digit) of the encounter..
        /// </summary>
        public static string ICD9DiagnosisCodes3digit_Description {
            get {
                return ResourceManager.GetString("ICD9DiagnosisCodes3digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-9 Diagnosis Codes (3 digit).
        /// </summary>
        public static string ICD9DiagnosisCodes3digit_Name {
            get {
                return ResourceManager.GetString("ICD9DiagnosisCodes3digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-9 Diagnosis codes (4 digit) of the encounter..
        /// </summary>
        public static string ICD9DiagnosisCodes4digit_Description {
            get {
                return ResourceManager.GetString("ICD9DiagnosisCodes4digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-9 Diagnosis Codes (4 digit).
        /// </summary>
        public static string ICD9DiagnosisCodes4digit_Name {
            get {
                return ResourceManager.GetString("ICD9DiagnosisCodes4digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-9 Diagnosis codes (5 digit) of the encounter..
        /// </summary>
        public static string ICD9DiagnosisCodes5digit_Description {
            get {
                return ResourceManager.GetString("ICD9DiagnosisCodes5digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-9 Diagnosis Codes (5 digit).
        /// </summary>
        public static string ICD9DiagnosisCodes5digit_Name {
            get {
                return ResourceManager.GetString("ICD9DiagnosisCodes5digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-9 Procedure codes (3 digit) of the encounter..
        /// </summary>
        public static string ICD9ProcedureCodes3digit_Description {
            get {
                return ResourceManager.GetString("ICD9ProcedureCodes3digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-9 Procedure Codes (3 digit).
        /// </summary>
        public static string ICD9ProcedureCodes3digit_Name {
            get {
                return ResourceManager.GetString("ICD9ProcedureCodes3digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported ICD-9 Procedure codes (4 digit) of the encounter..
        /// </summary>
        public static string ICD9ProcedureCodes4digit_Description {
            get {
                return ResourceManager.GetString("ICD9ProcedureCodes4digit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD-9 Procedure Codes (4 digit).
        /// </summary>
        public static string ICD9ProcedureCodes4digit_Name {
            get {
                return ResourceManager.GetString("ICD9ProcedureCodes4digit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database and universal standard for identifying medical laboratory observations..
        /// </summary>
        public static string LOINCLabTest_Description {
            get {
                return ResourceManager.GetString("LOINCLabTest_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOINC Lab Tests.
        /// </summary>
        public static string LOINCLabTest_Name {
            get {
                return ResourceManager.GetString("LOINCLabTest_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database and universal standard for identifying medical laboratory observations..
        /// </summary>
        public static string LOINCProcedure_Description {
            get {
                return ResourceManager.GetString("LOINCProcedure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOINC Procedures.
        /// </summary>
        public static string LOINCProcedure_Name {
            get {
                return ResourceManager.GetString("LOINCProcedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes Dates of the Metadata.
        /// </summary>
        public static string MetaDataRefresh_Description {
            get {
                return ResourceManager.GetString("MetaDataRefresh_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Refresh.
        /// </summary>
        public static string MetaDataRefresh_Name {
            get {
                return ResourceManager.GetString("MetaDataRefresh_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files for a modular program request..
        /// </summary>
        public static string ModularProgram_Description {
            get {
                return ResourceManager.GetString("ModularProgram_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modular Program File Upload.
        /// </summary>
        public static string ModularProgram_Name {
            get {
                return ResourceManager.GetString("ModularProgram_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The observation period of the encounter..
        /// </summary>
        public static string ObservationPeriod_Description {
            get {
                return ResourceManager.GetString("ObservationPeriod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Period.
        /// </summary>
        public static string ObservationPeriod_Name {
            get {
                return ResourceManager.GetString("ObservationPeriod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A free form catch all for any code the provider wishes to use..
        /// </summary>
        public static string OtherProcedure_Description {
            get {
                return ResourceManager.GetString("OtherProcedure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Procedure.
        /// </summary>
        public static string OtherProcedure_Name {
            get {
                return ResourceManager.GetString("OtherProcedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term to allow querying against the PRO_CM table for patient-reported outcome measures..
        /// </summary>
        public static string PatientReportedOutcome_Description {
            get {
                return ResourceManager.GetString("PatientReportedOutcome_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Reported Outcome (PRO).
        /// </summary>
        public static string PatientReportedOutcome_Name {
            get {
                return ResourceManager.GetString("PatientReportedOutcome_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term to allow the inclusion of Encounters based on PRO measures..
        /// </summary>
        public static string PatientReportedOutcomeEncounters_Description {
            get {
                return ResourceManager.GetString("PatientReportedOutcomeEncounters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Reported Outcome Encounters.
        /// </summary>
        public static string PatientReportedOutcomeEncounters_Name {
            get {
                return ResourceManager.GetString("PatientReportedOutcomeEncounters_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Codes for PCORI.
        /// </summary>
        public static string ProcedureCode_Description {
            get {
                return ResourceManager.GetString("ProcedureCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Codes.
        /// </summary>
        public static string ProcedureCode_Name {
            get {
                return ResourceManager.GetString("ProcedureCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A range of Quarterly Years for the patient subject of the encounter..
        /// </summary>
        public static string QuarterYear_Description {
            get {
                return ResourceManager.GetString("QuarterYear_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year/Quarter Observation Period.
        /// </summary>
        public static string QuarterYear_Name {
            get {
                return ResourceManager.GetString("QuarterYear_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported race of the patient subject..
        /// </summary>
        public static string Race_Description {
            get {
                return ResourceManager.GetString("Race_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string Race_Name {
            get {
                return ResourceManager.GetString("Race_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool for describing a series of events, starting an an index event..
        /// </summary>
        public static string RelativeTime_Description {
            get {
                return ResourceManager.GetString("RelativeTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Time.
        /// </summary>
        public static string RelativeTime_Name {
            get {
                return ResourceManager.GetString("RelativeTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of Settings for patient encounters..
        /// </summary>
        public static string Setting_Description {
            get {
                return ResourceManager.GetString("Setting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting_Name {
            get {
                return ResourceManager.GetString("Setting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reported sex of the patient subject..
        /// </summary>
        public static string Sex_Description {
            get {
                return ResourceManager.GetString("Sex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex_Name {
            get {
                return ResourceManager.GetString("Sex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A T-SQL script to execute on the data source..
        /// </summary>
        public static string SQL_Description {
            get {
                return ResourceManager.GetString("SQL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string SQL_Name {
            get {
                return ResourceManager.GetString("SQL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A T-SQL script to execute on the data source..
        /// </summary>
        public static string SQLDistibution_Description {
            get {
                return ResourceManager.GetString("SQLDistibution_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string SQLDistibution_Name {
            get {
                return ResourceManager.GetString("SQLDistibution_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient&apos;s time of birth..
        /// </summary>
        public static string TimeOfBirth_Description {
            get {
                return ResourceManager.GetString("TimeOfBirth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Birth.
        /// </summary>
        public static string TimeOfBirth_Name {
            get {
                return ResourceManager.GetString("TimeOfBirth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency of tobacco usage of the patient..
        /// </summary>
        public static string TobaccoUse_Description {
            get {
                return ResourceManager.GetString("TobaccoUse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco Use.
        /// </summary>
        public static string TobaccoUse_Name {
            get {
                return ResourceManager.GetString("TobaccoUse_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the trial the patient participated in..
        /// </summary>
        public static string Trial_Description {
            get {
                return ResourceManager.GetString("Trial_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string Trial_Name {
            get {
                return ResourceManager.GetString("Trial_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of unique visits for a patient typically combined with other terms..
        /// </summary>
        public static string Visits_Description {
            get {
                return ResourceManager.GetString("Visits_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string Visits_Name {
            get {
                return ResourceManager.GetString("Visits_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date the vitals measurement was taken..
        /// </summary>
        public static string VitalsMeasureDate_Description {
            get {
                return ResourceManager.GetString("VitalsMeasureDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vital Measure Observation Period.
        /// </summary>
        public static string VitalsMeasureDate_Name {
            get {
                return ResourceManager.GetString("VitalsMeasureDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weight of the patient..
        /// </summary>
        public static string Weight_Description {
            get {
                return ResourceManager.GetString("Weight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight_Name {
            get {
                return ResourceManager.GetString("Weight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A range of Years for the patient subject of the encounter..
        /// </summary>
        public static string Year_Description {
            get {
                return ResourceManager.GetString("Year_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Observation Period.
        /// </summary>
        public static string Year_Name {
            get {
                return ResourceManager.GetString("Year_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of geographical locations for patient encounters..
        /// </summary>
        public static string ZipCode_Description {
            get {
                return ResourceManager.GetString("ZipCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode_Name {
            get {
                return ResourceManager.GetString("ZipCode_Name", resourceCulture);
            }
        }
    }
}
