#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Audit.UI.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 2 "..\..\Views\PropertyFilterUI.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Audit;
    using Lpp.Audit.UI;
    using Lpp.Audit.UI.Models;
    using Lpp.Mvc;
    using Lpp.Utilities.Legacy;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PropertyFilterUI.cshtml")]
    public partial class PropertyFilterUI : System.Web.Mvc.WebViewPage<PropertyFilterUIModel>
    {

#line 88 "..\..\Views\PropertyFilterUI.cshtml"
public System.Web.WebPages.HelperResult Dropdowns( string id, IAuditProperty selectedProperty, PropertyValueComparison selectedComp )
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 89 "..\..\Views\PropertyFilterUI.cshtml"
 
    

#line default
#line hidden

#line 90 "..\..\Views\PropertyFilterUI.cshtml"
WriteTo(__razor_helper_writer, Html.DropDownList( "p" + id, Model.AllPossibleProperties.Select( x =>
        new SelectListItem { Text = x.Name, Value = x.ID.ToString(), Selected = x == selectedProperty } )
        .StartWith( new SelectListItem { Selected = selectedProperty == null, Value = "", Text = "select property" } ),
        new { @class = "Property" } ));


#line default
#line hidden

#line 93 "..\..\Views\PropertyFilterUI.cshtml"
                                     
    

#line default
#line hidden

#line 94 "..\..\Views\PropertyFilterUI.cshtml"
WriteTo(__razor_helper_writer, Html.DropDownList( "c" + id, Enum.GetValues( typeof( PropertyValueComparison ) ).Cast<PropertyValueComparison>().Select( c =>
        new SelectListItem { Text = c.ToString(), Value = c.ToString(), Selected = selectedComp == c } ),
        new { @class = "Comparison", style = "display: none" } ));


#line default
#line hidden

#line 96 "..\..\Views\PropertyFilterUI.cshtml"
                                                                


#line default
#line hidden
});

#line 97 "..\..\Views\PropertyFilterUI.cshtml"
}
#line default
#line hidden

        public PropertyFilterUI()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\PropertyFilterUI.cshtml"
  
    var id = Html.UniqueId();
    this.Stylesheet( "PropertyFilter.css" );

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var onChange_");

            
            #line 9 "..\..\Views\PropertyFilterUI.cshtml"
             Write(id);

            
            #line default
            #line hidden
WriteLiteral(" = (function() {\r\n        var state = [ ");

            
            #line 10 "..\..\Views\PropertyFilterUI.cshtml"
                 Write(string.Join( ",", Model.Properties.Select( p => "'" + p.ValueSelector.ValueAsString.Replace( ",", ",," ) + "'" ) ));

            
            #line default
            #line hidden
WriteLiteral(@" ];

        return function( index, value ) { 
            if ( typeof index == ""number"" ) state[index] = value;
            if ( index == ""remove"" && typeof value == ""number"" ) state.splice(value, 1);

            var val = 
                $.map( $("".");

            
            #line 17 "..\..\Views\PropertyFilterUI.cshtml"
                       Write(id);

            
            #line default
            #line hidden
WriteLiteral(@"""), function(row, idx) { 
                    var $row = $(row);
                    return $row.find("".Property"").val() + "":"" + $row.find("".Comparison"").val() + "":"" + (state[idx]||"""").replace(',',',,');
                } )
                .join();

            (");

            
            #line 23 "..\..\Views\PropertyFilterUI.cshtml"
        Write(Html.Raw(Model.OnChangeFunction));

            
            #line default
            #line hidden
WriteLiteral(")( val );\r\n        };\r\n    } )();\r\n\r\n    $(function() {\r\n        $(\"#");

            
            #line 28 "..\..\Views\PropertyFilterUI.cshtml"
        Write(id);

            
            #line default
            #line hidden
WriteLiteral("_add\").click( function() { \r\n            var $this = $(this);\r\n            $(\"#");

            
            #line 30 "..\..\Views\PropertyFilterUI.cshtml"
            Write(id);

            
            #line default
            #line hidden
WriteLiteral("_template\").clone().insertBefore( $this ).removeAttr(\"id\").addClass(\"");

            
            #line 30 "..\..\Views\PropertyFilterUI.cshtml"
                                                                                      Write(id);

            
            #line default
            #line hidden
WriteLiteral("\").show(); \r\n            $this.hide();\r\n        } );\r\n\r\n        $(\".");

            
            #line 34 "..\..\Views\PropertyFilterUI.cshtml"
        Write(id);

            
            #line default
            #line hidden
WriteLiteral(" > .Comparison\").live( \"change\", onChange_");

            
            #line 34 "..\..\Views\PropertyFilterUI.cshtml"
                                                       Write(id);

            
            #line default
            #line hidden
WriteLiteral(" );\r\n\r\n        $(\".");

            
            #line 36 "..\..\Views\PropertyFilterUI.cshtml"
        Write(id);

            
            #line default
            #line hidden
WriteLiteral(" > .Remove\").live( \"click\", function() {\r\n            var $this = $(this);\r\n     " +
"       var row = $this.parent();\r\n            var index = row.parent().children(" +
").index(row);\r\n            if ( !row.find(\".Property > option:first\").attr(\"valu" +
"e\") ) $(\"#");

            
            #line 40 "..\..\Views\PropertyFilterUI.cshtml"
                                                                       Write(id);

            
            #line default
            #line hidden
WriteLiteral("_add\").show();\r\n            row.remove();\r\n            onChange_");

            
            #line 42 "..\..\Views\PropertyFilterUI.cshtml"
                 Write(id);

            
            #line default
            #line hidden
WriteLiteral("( \"remove\", index );\r\n        } );\r\n\r\n        $(\".");

            
            #line 45 "..\..\Views\PropertyFilterUI.cshtml"
        Write(id);

            
            #line default
            #line hidden
WriteLiteral(" > .Property\").live( \"change\", function() {\r\n            var firstOption = $( \"op" +
"tion:first\", this );\r\n            if ( !firstOption.attr(\"value\") ) {\r\n         " +
"       firstOption.remove();\r\n                $(\"#");

            
            #line 49 "..\..\Views\PropertyFilterUI.cshtml"
                Write(id);

            
            #line default
            #line hidden
WriteLiteral(@"_add"").show();
            }

            var $this = $(this);
            var row = $this.parent();
            $( "".Comparison"", row ).show();
            var propId = $this.val();
            var index = row.parent().children().index(row);
            row.find("".Value"").remove()
            var placeholder = $(""<span>Loading...</span>"").appendTo( row );
            $.get( '");

            
            #line 59 "..\..\Views\PropertyFilterUI.cshtml"
               Write(Html.Raw(Url.Action<PropertyValueSelectorsController>( c => 
                        c.GetSelector( "__prop__", string.Format( "function(value){{onChange_{0}(__index__,value);}}", id ) ))
                        .Replace( "__prop__", "'+propId+'" ).Replace( "__index__", "'+index+'" )
                    ));

            
            #line default
            #line hidden
WriteLiteral("\', \r\n                    function(sel) { placeholder.replaceWith( \"<div class=\\\"V" +
"alue\\\">\" + sel + \"</div>\" ); } \r\n            );\r\n        } );\r\n    });\r\n</script" +
">\r\n\r\n<div");

WriteLiteral(" class=\"PropertyFilter\"");

WriteLiteral(">\r\n");

            
            #line 70 "..\..\Views\PropertyFilterUI.cshtml"
    
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\PropertyFilterUI.cshtml"
       var index = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 71 "..\..\Views\PropertyFilterUI.cshtml"
    
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\PropertyFilterUI.cshtml"
     foreach( var p in Model.Properties )
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2868), Tuple.Create("\"", 2883)
            
            #line 73 "..\..\Views\PropertyFilterUI.cshtml"
, Tuple.Create(Tuple.Create("", 2876), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 2876), false)
, Tuple.Create(Tuple.Create(" ", 2879), Tuple.Create("Row", 2880), true)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Remove\"");

WriteLiteral(">[x]</div>\r\n");

WriteLiteral("            ");

            
            #line 75 "..\..\Views\PropertyFilterUI.cshtml"
       Write(Dropdowns( id, p.Property, p.Comparison ));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"Value\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 77 "..\..\Views\PropertyFilterUI.cshtml"
           Write(p.ValueSelector.Render( Html, string.Format( "function( value ) {{ onChange_{0}( {1}, value ); }}", id, index ) ));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 80 "..\..\Views\PropertyFilterUI.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 3202), Tuple.Create("\"", 3221)
            
            #line 81 "..\..\Views\PropertyFilterUI.cshtml"
, Tuple.Create(Tuple.Create("", 3207), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 3207), false)
, Tuple.Create(Tuple.Create("", 3212), Tuple.Create("_template", 3212), true)
);

WriteLiteral(" style=\"display: none\"");

WriteLiteral(" class=\"Row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"Remove\"");

WriteLiteral(">[x]</div>\r\n");

WriteLiteral("        ");

            
            #line 83 "..\..\Views\PropertyFilterUI.cshtml"
   Write(Dropdowns( id, null, PropertyValueComparison.Eq ));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"Add\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3402), Tuple.Create("\"", 3416)
            
            #line 85 "..\..\Views\PropertyFilterUI.cshtml"
, Tuple.Create(Tuple.Create("", 3407), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 3407), false)
, Tuple.Create(Tuple.Create("", 3412), Tuple.Create("_add", 3412), true)
);

WriteLiteral(">Add Property...</a></div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
