#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.HealthCare.I2B2.Views.I2B2QueryBuilder
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns.HealthCare.Controllers;
    using Lpp.Dns.HealthCare.I2B2;
    using Lpp.Dns.HealthCare.I2B2.Models;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/I2B2QueryBuilder/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<Lpp.Dns.HealthCare.I2B2.Models.I2B2Model>
    {
        public Create()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\I2B2QueryBuilder\Create.cshtml"
   this.Stylesheet( "I2B2.css" ); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"MedicalRequest ui-form\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui-form\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"ReportType\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"ui-groupbox\"");

WriteLiteral(">\r\n            \r\n        </div>\r\n\r\n    </div>\r\n\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
