#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.Portal.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/WhatsNew.cshtml")]
    public partial class WhatsNew : System.Web.Mvc.WebViewPage<dynamic>
    {
        public WhatsNew()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\WhatsNew.cshtml"
   Layout = null; 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<ul>\r\n    <li>PopMedNet 3.2 Feature Enhancements:\r\n        <ul>\r\n            " +
"<li> Projects - Project based request processing and administration</li>\r\n      " +
"  </ul>\r\n    </li>\r\n    <li>PopMedNet 3.1 Feature Enhancements:\r\n        <ul>\r\n " +
"           <li> User Workspaces - Built-in folders that allow requests to be aut" +
"omatically organized into sub-folders</li>\r\n            <li> Shared Folders -  A" +
"llows users to share requests with other users.</li>\r\n            <li> Network N" +
"avigator - Visual tools network browser that allows the user to navigate through" +
" the network hierarchy.</li>\r\n            <li> Bread-crumb Navigation Control - " +
"Control the maintains position within the network hierarchy providing context an" +
"d allowing the user to easily back up through the hierarchy</li>\r\n            <l" +
"i> Sticky User Settings - Remembers users settings, such as collapsible controls" +
", the number of requests shown on the request page will be remember from session" +
" to session.</li>\r\n            <li> Auto DataMart Configuration - this will make" +
" it easier for datamart administrators to configure their datamart client. This " +
"feature streamlines the datamart client configuration process as it can be done " +
"from the portal.</li>\r\n            <li> User Registration - Allows users to regi" +
"ster for an account by entering contact information, username, and password in a" +
"ddition to the traditional user creation process performed by Administrators.</l" +
"i>\r\n            <li> User registration Workflow Process - User registration requ" +
"ests enter a task based workflow process used by Administrators to approve or re" +
"ject user registrations via a new Task panel displayed on the home page.</li>\r\n " +
"       </ul>\r\n    </li>\r\n    <li>PopMedNet 3.0 ONC Query Health Enhancements:\r\n " +
"       <ul>\r\n            <li>Query Envelope - Formalization of the PMN request t" +
"unnel to comply with ONC Query Health requirements</li>\r\n            <li>Enhance" +
"d Security - Implementation of mutual authentication over TLS using X.509 certif" +
"icates</li>\r\n            <li>I2B2 Request Plugin - Integration of I2B2 request c" +
"omposer that submits request to the PMN network that are routed to I2B2 end-poin" +
"ts used to process the request</li>\r\n        </ul>\r\n    </li>\r\n    <li>MDPHnet F" +
"eature Enhancements:\r\n        <ul>\r\n            <li>Menu-driven query builder re" +
"quest plugin used to compose ICD-9 Diagnosis requests and Reportable Disease Req" +
"uests submitted against ESP databases.</li>\r\n        </ul>\r\n    </li>\r\n    <li>P" +
"opMedNet 3.0 Design and Technical enhancements:\r\n        <ul>\r\n            <li>N" +
"ew Request Model Plug-in architecture allowing the application to be easily exte" +
"nded to accommodate new request types and data models.</li>\r\n            <li>Upg" +
"raded technology platform that includes Microsoft .NET 4, Entity Framework 4,\r\n " +
"               MVC 3, WCF, and MEF under Visual Studio 2010 solution.</li>\r\n    " +
"        <li>Consolidation of all request and response data into documents that m" +
"ay be displayed\r\n                using built-in viewer or downloaded to for use " +
"by custom applications.</li>\r\n            <li>Redesigned/rewritten DataMart Clie" +
"nt application that uses a simplified threading\r\n                model to proces" +
"s requests.</li>\r\n            <li>Use of the Windows Credential Manager to store" +
" local DataMart Client credentials.</li>\r\n        </ul>\r\n    </li>\r\n</ul>");

        }
    }
}
#pragma warning restore 1591
