IF EXISTS(SELECT * FROM [Projects] WHERE Name = 'Mini-Sentinel' )
BEGIN

DECLARE @SID VARCHAR(max)
SET @SID=(SELECT TOP 1 SID FROM [Projects] WHERE Name='Mini-Sentinel')

--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3, '03','03' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3001, '2. A) New Molecular Entities (NMEs)','',@SID, 3)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 3001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3001001, 'Saxagliptan','',@SID, 3001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 3001002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3001002, 'Dabigatran','',@SID, 3001)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3002, '2. B) Drugs on the Market for >2 years','',@SID, 3)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 3002001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3002001, 'Angiodema','',@SID, 3002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 3002002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3002002, 'Asenapine-Aripiprazole','',@SID, 3002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 3002003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3002003, 'Stalevo','',@SID, 3002)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3003, '2. C) Evaluation of Effects of FDA’s Regulatory Actions','',@SID, 3)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 3003001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3003001, 'LABA','',@SID, 3003)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3004, '2. D) Drug Use Studies - Comparison to Nationally Projected Databases','',@SID, 3)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 3004001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (3004001, 'Drug Use','',@SID, 3004)

--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4, '04','04' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4001, '2. A) HOI Validation/Adjudication','',@SID, 4)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 4001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4001001, 'Anaphylaxis','',@SID, 4001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 4001002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4001002, 'Severe Liver Injury','',@SID, 4001)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4002, '2. B) Statistical Methods Development ','',@SID, 4)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 4002001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4002001, 'Taxonomy','',@SID, 4002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 4002002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4002002, 'Evaluating Strategies for Data Sharing and Analyses in Distributed Data Settings','',@SID, 4002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 4002003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4002003, 'Methods to Evaluate Impact of FDA Regulatory Actions','',@SID, 4002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 4002004)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4002004, 'Framework for Assessment of Signal Refinement Positive Results','',@SID, 4002)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4003, '2. C) Linking of Distributed Database Environments ','',@SID, 4)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 4003001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (4003001, 'Anonymous Linking','',@SID, 4003)


--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6, '06','06' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6001, 'Task 1: Define the surveillance population and create the distributed database','',@SID, 6)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 6001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6001001, 'Phase 1','',@SID, 6001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 6001002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6001002, 'Phase 2','',@SID, 6001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 6001003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6001003, 'Phase 3','',@SID, 6001)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6002, 'Task 2: Characterize the Blood-SCAN distributed database','',@SID, 6)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 6002001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6002001, 'Exposures','',@SID, 6002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 6002002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6002002, 'Outcomes','',@SID, 6002)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6003, 'Task 3: Conduct an evaluation for thromboembolic events (TEE) after immunoglobulin administration, ','',@SID, 6)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 6003001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (6003001, 'IVIG','',@SID, 6003)


--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7, '07','07' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7001, '2. A) New Molecular Entities (NMEs)','',@SID, 7)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7001001, 'Saxagliptan-Sitagliptan AMI','',@SID, 7001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7001002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7001002, 'Dabigatran','',@SID, 7001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7001003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7001003, 'Asenapine-Aripiprazole','',@SID, 7001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7001004)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7001004, 'Mirabegron/PROMPT 2 MP3','',@SID, 7001)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7002, '2. B) Drugs on the Market for >2 years','',@SID, 7)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7002001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7002001, 'Antipsychotics-Youths Subproject 1','',@SID, 7002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7002002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7002002, 'Antipsychotics-Youths Subproject 2','',@SID, 7002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7002003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7002003, 'Antifungals and Severe Liver Injury-terminated post-feasibility assessment per FDA','',@SID, 7002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7002004)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7002004, 'Parenteral Iron and Anaphylaxis','',@SID, 7002)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7003, '2. D) Drug Use Studies - Comparison to Nationally Projected Databases','',@SID, 7)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 7003001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (7003001, 'Drug Use','',@SID, 7003)


--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8, '08','08' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8001, '2. A) HOI Validation/Adjudication','',@SID, 8)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8001001, 'Acute Kidney Injury','',@SID, 8001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8001002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8001002, 'Thromboembolism','',@SID, 8001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8001003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8001003, 'Atrial Fibrillation','',@SID, 8001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8001004)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8001004, 'Hemolytic Anemia','',@SID, 8001)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8002, '2. B) Alternative Approaches for HOI Validation','',@SID, 8)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8002001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8002001, 'Alternative Approaches','',@SID, 8002)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8003, '2. C) Surveillance Preparedness','',@SID, 8)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8003001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8003001, '15 HOIs','',@SID, 8003)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8003002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8003002, '15 Cohorts','',@SID, 8003)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8004, '2. D) Extension of Methods Taxonomy','',@SID, 8)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8004001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8004001, 'Taxonomy','',@SID, 8004)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8005, '2. E) Methods Development','',@SID, 8)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8005001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8005001, 'Confounder Adjustment','',@SID, 8005)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8005002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8005002, 'Supplemental Info','',@SID, 8005)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8005003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8005003, 'PROMPT 3/Sequential Methods','',@SID, 8005)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8006, '2. F) Routine Surveillance','',@SID, 8)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8006001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8006001, 'PROMPT 1/Self-ControlDesign','',@SID, 8006)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 8006002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (8006002, 'PROMPT 2/HDPS','',@SID, 8006)


--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9, '09','09' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9001, '1. Update the MSCDM','',@SID, 9)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 9001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9001001, 'Core data','',@SID, 9001)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9002, '1a. Update the MSCDM','',@SID, 9)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 9002001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9002001, 'Clinical data','',@SID, 9002)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9003, '2a. Prepare Summary Tables for the Query Tool','',@SID, 9)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 9003001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9003001, 'Run SAS programs to Create/Update Summary Tables after each Data Refresh','',@SID, 9003)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9004, '2b. Maintain Operation of the Mini-Sentinel Query Tool ','',@SID, 9)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 9004001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9004001, 'Maintain Data Mart Client','',@SID, 9004)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9005, '2c. Program Development and Testing ','',@SID, 9)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 9005001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9005001, 'Beta testing','',@SID, 9005)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9006, '3a. Establish Capacity for Timely Response to MSOC Queries','',@SID, 9)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 9006001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9006001, 'Production MP, ST, PROMPT and  Ad Hoc requests','',@SID, 9006)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9007, '3b. Respond to Ad Hoc MSOC Questions and Requests','',@SID, 9)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 9007001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (9007001, 'Surveys','',@SID, 9007)



--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (10, '10','10' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (10001, '4. Task 1 - Development of Modular Programs Modified with  ','',@SID, 10)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 10001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (10001001, 'Daily Dosing Module','',@SID, 10001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 10001002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (10001002, 'Frequency Module','',@SID, 10001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 10001003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (10001003, 'Encounter Type - Primary Diagnosis Flag Module','',@SID, 10001)


--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (11, '11','11' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (11001, 'Evaluating Blood-SCAN Findings through Chart Review','',@SID, 11)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 11001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (11001001, 'Thromboembolic','',@SID, 11001)


--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12, '12','12' , @SID , null)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12001, '3. Expansion of Routine Surveillance Capabilities','',@SID, 12)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12001001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12001001, '1) Identify high priority HOI, cohort, and confounders','',@SID, 12001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12001002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12001002, '2) Develop an approach for incorporation of algorithms into existing modular programs','',@SID, 12001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12001003)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12001003, '3) Create up to 5 complex and 3 modular algorithms','',@SID, 12001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12001004)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12001004, '4) Incorporating algorithms into active surveillance modules','',@SID, 12001)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12001005)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12001005, '5) Test the active surveillance modules','',@SID, 12001)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12002, '5. Create Capacity for Implementation of Routine Surveillance ','',@SID, 12)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12002001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12002001, 'Routine Surveillance-Rivaroxaban','',@SID, 12002)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12002002)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12002002, 'Modular Programs >=61','',@SID, 12002)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12003, '6. Developing Approaches for Randomization within MSDD','',@SID, 12)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12003001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12003001, 'Randomization Approaches','',@SID, 12003)
--INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12004, '7. Implementing Efficiencies to Improve the Query Fulfillment ','',@SID, 12)
	IF NOT EXISTS (SELECT 1 FROM [Activities] WHERE [Id]= 12004001)
		INSERT INTO [Activities] ([Id] ,[Name] ,[Description] ,[ProjectId] ,[ParentId]) VALUES (12004001, 'Query Improvement','',@SID, 12004)

END
GO

IF NOT EXISTS(SELECT NULL FROM MigrationScript WHERE ScriptRun = '084.2013.10.10')
BEGIN
	INSERT [MigrationScript]([Date],[ScriptRun]) VALUES (GetDate(), '084.2013.10.10')
END
GO