#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.HealthCare.Conditions.Views.Conditions
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    
    #line 1 "..\..\Views\Conditions\Config.cshtml"
    using Lpp.Dns;
    
    #line default
    #line hidden
    using Lpp.Dns.HealthCare.Conditions;
    using Lpp.Dns.HealthCare.Conditions.Models;
    using Lpp.Dns.HealthCare.Controllers;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    using Lpp.Utilities.Legacy;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Conditions/Config.cshtml")]
    public partial class Config : System.Web.Mvc.WebViewPage<ConfigModel>
    {
        public Config()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Conditions\Config.cshtml"
  
    Layout = null;
    var id = Html.UniqueId();

            
            #line default
            #line hidden
WriteLiteral(" \r\n\r\n<div");

WriteLiteral(" class=\"Value ModelConfigForm\"");

WriteAttribute("id", Tuple.Create(" id=\"", 131), Tuple.Create("\"", 139)
            
            #line 8 "..\..\Views\Conditions\Config.cshtml"
, Tuple.Create(Tuple.Create("", 136), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 136), false)
);

WriteLiteral(">\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"Link\"");

WriteLiteral(">[configure]</a>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            var dlg = $(\"#");

            
            #line 12 "..\..\Views\Conditions\Config.cshtml"
                      Write(id);

            
            #line default
            #line hidden
WriteLiteral(" > .ModelConfig\");\r\n            var link = $(\"#");

            
            #line 13 "..\..\Views\Conditions\Config.cshtml"
                       Write(id);

            
            #line default
            #line hidden
WriteLiteral(" > a.Link\");\r\n            link.click(function () {\r\n                dlg.dialog({\r" +
"\n                    modal: true, title: \"");

            
            #line 16 "..\..\Views\Conditions\Config.cshtml"
                                    Write(Model.Model.Name);

            
            #line default
            #line hidden
WriteLiteral(@""",
                    width: 540, buttons: {
                        OK: function () {
                            dlg.dialog(""close"");
                        },
                        Cancel: function () { dlg.dialog(""close""); }
                    }
                });
                return false;
            });
        });
    </script>

    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 843), Tuple.Create("\"", 863)
            
            #line 29 "..\..\Views\Conditions\Config.cshtml"
, Tuple.Create(Tuple.Create("", 848), Tuple.Create<System.Object, System.Int32>(Model.Model.ID
            
            #line default
            #line hidden
, 848), false)
);

WriteLiteral(" class=\"ModelConfig\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui-groupbox\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui-dialog-groupbox-header\"");

WriteLiteral("><span>Data Source</span></div>\r\n            <div");

WriteLiteral(" class=\"ui-form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Field\"");

WriteLiteral(">\r\n                    <label>Server</label>\r\n                    <input");

WriteLiteral(" id=\"Server\"");

WriteLiteral(" name=\"Server\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1207), Tuple.Create("\"", 1290)
            
            #line 35 "..\..\Views\Conditions\Config.cshtml"
, Tuple.Create(Tuple.Create("", 1215), Tuple.Create<System.Object, System.Int32>(Model.Properties.ContainsKey("Server") ? Model.Properties["Server"] : ""
            
            #line default
            #line hidden
, 1215), false)
);

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"Field\"");

WriteLiteral(">\r\n                    <label>Port</label>\r\n                    <input");

WriteLiteral(" id=\"Port\"");

WriteLiteral(" name=\"Port\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1458), Tuple.Create("\"", 1537)
            
            #line 39 "..\..\Views\Conditions\Config.cshtml"
, Tuple.Create(Tuple.Create("", 1466), Tuple.Create<System.Object, System.Int32>(Model.Properties.ContainsKey("Port") ? Model.Properties["Port"] : ""
            
            #line default
            #line hidden
, 1466), false)
);

WriteLiteral(" />\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"Field\"");

WriteLiteral(">\r\n                    <label>User ID</label>\r\n                    <input");

WriteLiteral(" id=\"UserId\"");

WriteLiteral(" name=\"UserId\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1714), Tuple.Create("\"", 1797)
            
            #line 44 "..\..\Views\Conditions\Config.cshtml"
, Tuple.Create(Tuple.Create("", 1722), Tuple.Create<System.Object, System.Int32>(Model.Properties.ContainsKey("UserId") ? Model.Properties["UserId"] : ""
            
            #line default
            #line hidden
, 1722), false)
);

WriteLiteral(" />\r\n                </div>\r\n                <br />\r\n\r\n                <div");

WriteLiteral(" class=\"Field\"");

WriteLiteral(">\r\n                    <label>Password</label>\r\n                    <input");

WriteLiteral(" id=\"Password\"");

WriteLiteral(" name=\"Password\"");

WriteLiteral(" type=\"password\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2007), Tuple.Create("\"", 2094)
            
            #line 50 "..\..\Views\Conditions\Config.cshtml"
 , Tuple.Create(Tuple.Create("", 2015), Tuple.Create<System.Object, System.Int32>(Model.Properties.ContainsKey("Password") ? Model.Properties["Password"] : ""
            
            #line default
            #line hidden
, 2015), false)
);

WriteLiteral(" />\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"Field\"");

WriteLiteral(">\r\n                    <label>Confirm Password</label>\r\n                    <inpu" +
"t");

WriteLiteral(" id=\"ConfirmPassword\"");

WriteLiteral(" name=\"ConfirmPassword\"");

WriteLiteral(" type=\"password\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2302), Tuple.Create("\"", 2403)
            
            #line 55 "..\..\Views\Conditions\Config.cshtml"
               , Tuple.Create(Tuple.Create("", 2310), Tuple.Create<System.Object, System.Int32>(Model.Properties.ContainsKey("ConfirmPassword") ? Model.Properties["ConfirmPassword"] : ""
            
            #line default
            #line hidden
, 2310), false)
);

WriteLiteral(" />\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"Field\"");

WriteLiteral(">\r\n                    <label>Database</label>\r\n                    <input");

WriteLiteral(" id=\"Database\"");

WriteLiteral(" name=\"Database\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2585), Tuple.Create("\"", 2672)
            
            #line 60 "..\..\Views\Conditions\Config.cshtml"
, Tuple.Create(Tuple.Create("", 2593), Tuple.Create<System.Object, System.Int32>(Model.Properties.ContainsKey("Database") ? Model.Properties["Database"] : ""
            
            #line default
            #line hidden
, 2593), false)
);

WriteLiteral(" />\r\n                </div>\r\n                <br />\r\n\r\n                <div");

WriteLiteral(" class=\"Field\"");

WriteLiteral(">\r\n                    <label>Connection Timeout</label>\r\n                    <in" +
"put");

WriteLiteral(" id=\"ConnectionTimeout\"");

WriteLiteral(" name=\"ConnectionTimeout\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2906), Tuple.Create("\"", 3013)
            
            #line 66 "..\..\Views\Conditions\Config.cshtml"
               , Tuple.Create(Tuple.Create("", 2914), Tuple.Create<System.Object, System.Int32>(Model.Properties.ContainsKey("ConnectionTimeout") ? Model.Properties["ConnectionTimeout"] : "15"
            
            #line default
            #line hidden
, 2914), false)
);

WriteLiteral(" />\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"Field\"");

WriteLiteral(">\r\n                    <label>Command Timeout</label>\r\n                    <input" +
"");

WriteLiteral(" id=\"CommandTimeout\"");

WriteLiteral(" name=\"CommandTimeout\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3214), Tuple.Create("\"", 3316)
            
            #line 71 "..\..\Views\Conditions\Config.cshtml"
         , Tuple.Create(Tuple.Create("", 3222), Tuple.Create<System.Object, System.Int32>(Model.Properties.ContainsKey("CommandTimeout") ? Model.Properties["CommandTimeout"] : "120"
            
            #line default
            #line hidden
, 3222), false)
);

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</" +
"div>");

        }
    }
}
#pragma warning restore 1591
