//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lpp.Dns.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table AuditEvents
        ///(
        ///	Id int identity primary key,
        ///	KindId uniqueidentifier not null,
        ///	[Time] datetime not null default getdate(),
        ///	TargetId1 uniqueidentifier not null default &apos;00000000-0000-0000-0000-000000000000&apos;,
        ///	TargetId2 uniqueidentifier not null default &apos;00000000-0000-0000-0000-000000000000&apos;,
        ///	TargetId3 uniqueidentifier not null default &apos;00000000-0000-0000-0000-000000000000&apos;,
        ///	TargetId4 uniqueidentifier not null default &apos;00000000-0000-0000-0000-000000000000&apos;,
        ///	TargetId5 uniqueidentifie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuditDDL {
            get {
                return ResourceManager.GetString("AuditDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  FullTextCatalog [Full_Text_Catalog]    Script Date: 02/03/2012 12:57:29 ******/
        ///CREATE FULLTEXT CATALOG [Full_Text_Catalog]WITH ACCENT_SENSITIVITY = ON
        ///AS DEFAULT
        ///AUTHORIZATION [dbo]
        ///GO
        ////****** Object:  Table [dbo].[Organizations]    Script Date: 02/03/2012 12:57:31 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///SET ANSI_PADDING ON
        ///GO
        ///CREATE TABLE [dbo].[Organizations](
        ///	[OrganizationId] [int] IDENTITY(1,1) NOT NULL,
        ///	[OrganizationName] [varchar](100) NULL,
        ///	[IsDele [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DNS3_a_BaseStructure {
            get {
                return ResourceManager.GetString("DNS3_a_BaseStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_configure &apos;show advanced options&apos;, 1;
        ///GO
        ///RECONFIGURE;
        ///GO
        ///sp_configure &apos;clr enabled&apos;, 1;
        ///GO
        ///RECONFIGURE;
        ///GO
        ///
        ///create table Activities ( Id int identity primary key, Name nvarchar(max) )
        ///GO
        ///
        ///alter table Queries add ActivityId int null references Activities
        ///alter table Queries add IsScheduled bit not null default 0
        ///alter table queries alter column QueryTypeId int null
        ///alter table queries add RequestTypeId uniqueidentifier not null
        ///alter table queries add Submitted datetime null
        ///alter table q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DNS4_a_Diff {
            get {
                return ResourceManager.GetString("DNS4_a_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from aclentries
        ///delete from securitymembership
        ///delete from securityinheritance
        ///delete from securitytargets
        ///delete from securitygroups
        ///go
        ///
        ///declare @allUsers uniqueidentifier, @allDms uniqueidentifier, @allOrgs uniqueidentifier, @portal uniqueidentifier, @allGroups uniqueidentifier
        ///declare @manageAcl uniqueidentifier, @login uniqueidentifier
        ///set @allUsers = &apos;1D3A0001-4717-40A3-98A1-A22100FDE0ED&apos;
        ///set @portal = &apos;BBBA0001-2BC2-4E12-A5B4-A22100FDBAFD&apos;
        ///set @allDms = &apos;7A0C0001-B9A3-4F4B-9855-A2210 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DNS4_c_SecInitialize {
            get {
                return ResourceManager.GetString("DNS4_c_SecInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --In terms of membership, security subjects comprise a Directed Acyclic Graph (DAG).
        ///--It is directed, because &quot;A is member of B&quot; does not mean &quot;B is member of A&quot;.
        ///--It is acyclic, because no group can be a member of itself, either directly or through other groups.
        ///
        ///--In terms of inhertance, security objects comprise a tree (or, rather, a forest of trees),
        ///--which is a special case of DAG.
        ///--Therefore, both membership and inheritance can be represented as a DAG.
        ///
        ///--Representing and efficiently query [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecurityDAGs {
            get {
                return ResourceManager.GetString("SecurityDAGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [SecurityTargets](
        ///	[Id] [int] IDENTITY(1,1) primary key NOT NULL,
        ///	[Arity] int not null default 1,
        ///	[ObjectId1] uniqueidentifier not null default &apos;00000000-0000-0000-0000-000000000000&apos;,
        ///	[ObjectId2] uniqueidentifier not null default &apos;00000000-0000-0000-0000-000000000000&apos;,
        ///	[ObjectId3] uniqueidentifier not null default &apos;00000000-0000-0000-0000-000000000000&apos;,
        ///	[ObjectId4] uniqueidentifier not null default &apos;00000000-0000-0000-0000-000000000000&apos;,
        ///	[ObjectId5] uniqueidentifier not null defau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecurityDDL {
            get {
                return ResourceManager.GetString("SecurityDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- This file contains SQL views for producing object tuples of different sizes with their corresponding ACL entries.
        ///
        ///	-------------------------------------------------------------------------------
        ///	-- SecurityInheritanceClosure2 - an exact duplicate of the SecurityInheritanceClosure table
        ///	-------------------------------------------------------------------------------
        ///	create table SecurityInheritanceClosure2( [Start] uniqueidentifier not null, [End] uniqueidentifier not null, [Distance] int not null [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecurityTupleViews {
            get {
                return ResourceManager.GetString("SecurityTupleViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into QueryStatusTypes( QueryStatusTypeId, QueryStatusType ) values( 1, &apos;Pending&apos; )
        ///insert into QueryStatusTypes( QueryStatusTypeId, QueryStatusType ) values( 2, &apos;Submitted&apos; )
        ///insert into QueryStatusTypes( QueryStatusTypeId, QueryStatusType ) values( 3, &apos;Completed&apos; )
        ///insert into QueryCategory( QueryCategoryId, QueryCategory ) values( 1, &apos;Dummy&apos; )
        ///insert into DataMartTypes( DataMartTypeId, DataMartType ) values( 1, &apos;Dummy&apos; ).
        /// </summary>
        internal static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
    }
}
