#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.General.Metadata.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns.General.Metadata;
    using Lpp.Dns.General.Metadata.Models;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CreateRegSearch.cshtml")]
    public partial class CreateRegSearch : System.Web.Mvc.WebViewPage<Lpp.Dns.General.Metadata.Models.MetadataRegSearchModel>
    {
        public CreateRegSearch()
        {
        }
        public override void Execute()
        {

WriteLiteral("<input type=\"hidden\" id=\"hData\" name=\"Data\" /> <!--The entire model is stored in " +
"here as json-->\r\n<div class=\"ui-groupbox\" id=\"registrySearch\">\r\n    <div class=\"" +
"ui-groupbox-header\"><span>Search Criteria</span></div>\r\n\r\n    <fieldset class=\"u" +
"i-groupbox\">\r\n        <legend></legend>\r\n        <div class=\"ui-groupbox-header\"" +
"><span>Registry Items</span></div>\r\n        <ol>\r\n            <li>\r\n            " +
"    <label for=\"txtName\">Name</label>\r\n                <input type=\"text\" id=\"tx" +
"tName\" data-bind=\"value: Name\" style=\"width: 100%;\" />\r\n            </li>\r\n     " +
"       <li><span>Classification</span></li>\r\n            <li class=\"col3\">\r\n    " +
"            <label for=\"chkClassificationDiseaseDisorderCondition\">\r\n           " +
"         <input type=\"checkbox\" id=\"chkClassificationDiseaseDisorderCondition\" d" +
"ata-bind=\"checked: ClassificationDiseaseDisorderCondition\" />\r\n                 " +
"   Disease/Disorder/Condition\r\n                </label>\r\n            </li>\r\n    " +
"        <li class=\"col3\">\r\n                <label for=\"chkClassificationRareDise" +
"aseDisorderCondition\">\r\n                    <input type=\"checkbox\" id=\"chkRareCl" +
"assificationDiseaseDisorderCondition\" data-bind=\"checked: ClassificationRareDise" +
"aseDisorderCondition\" />\r\n                    Rare Disease/Disorder/Condition\r\n " +
"               </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n     " +
"           <label for=\"chkClassificationPregnancy\">\r\n                    <input " +
"type=\"checkbox\" id=\"chkClassificationPregnancy\" data-bind=\"checked: Classificati" +
"onPregnancy\" />\r\n                    Pregnancy\r\n                </label>\r\n      " +
"      </li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkClass" +
"ificationProductBiologic\">\r\n                    <input type=\"checkbox\" id=\"chkCl" +
"assificationProductBiologic\" data-bind=\"checked: ClassificationProductBiologic\" " +
"/>\r\n                    Product,Biologic\r\n                </label>\r\n            " +
"</li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkClassificat" +
"ionProductDevice\">\r\n                    <input type=\"checkbox\" id=\"chkClassifica" +
"tionProductDevice\" data-bind=\"checked: ClassificationProductDevice\" />\r\n        " +
"            Product,Device\r\n                </label>\r\n            </li>\r\n       " +
"     <li class=\"col3\">\r\n                <label for=\"chkClassificationProductDrug" +
"\">\r\n                    <input type=\"checkbox\" id=\"chkClassificationProductDrug\"" +
" data-bind=\"checked: ClassificationProductDrug\" />\r\n                    Product," +
"Drug\r\n                </label>\r\n            </li>\r\n            <li class=\"col3\">" +
"\r\n                <label for=\"chkClassificationServiceEncounter\">\r\n             " +
"       <input type=\"checkbox\" id=\"chkClassificationServiceEncounter\" data-bind=\"" +
"checked: ClassificationServiceEncounter\" />\r\n                    Service,Encount" +
"er\r\n                </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n" +
"                <label for=\"chkClassificationServiceHospitalization\">\r\n         " +
"           <input type=\"checkbox\" id=\"chkClassificationServiceHospitalization\" d" +
"ata-bind=\"checked: ClassificationServiceHospitalization\" />\r\n                   " +
" Service,Hospitalization\r\n                </label>\r\n            </li>\r\n         " +
"   <li class=\"col3\">\r\n                <label for=\"chkClassificationServiceProced" +
"ure\">\r\n                    <input type=\"checkbox\" id=\"chkClassificationServicePr" +
"ocedure\" data-bind=\"checked: ClassificationServiceProcedure\" />\r\n               " +
"     Service,Procedure\r\n                </label>\r\n            </li>\r\n           " +
" <li class=\"col3\">\r\n                <label for=\"chkClassificationTransplant\">\r\n " +
"                   <input type=\"checkbox\" id=\"chkClassificationTransplant\" data-" +
"bind=\"checked: ClassificationTransplant\" />\r\n                    Transplant\r\n   " +
"             </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n       " +
"         <label for=\"chkClassificationTumor\">\r\n                    <input type=\"" +
"checkbox\" id=\"chkClassificationTumor\" data-bind=\"checked: ClassificationTumor\" /" +
">\r\n                    Tumor\r\n                </label>\r\n            </li>\r\n     " +
"       <li class=\"col3\">\r\n                <label for=\"chkClassificationVaccine\">" +
"\r\n                    <input type=\"checkbox\" id=\"chkClassificationVaccine\" data-" +
"bind=\"checked: ClassificationVaccine\" />\r\n                    Vaccine\r\n         " +
"       </label>\r\n            </li>\r\n        </ol>\r\n        <br style=\"clear:both" +
"\" />\r\n        <ol>\r\n            <li><span>Purpose</span></li>\r\n            <li c" +
"lass=\"col3\">\r\n                <label for=\"chkPurposeClinicalPracticeAssessment\">" +
"\r\n                    <input type=\"checkbox\" id=\"chkPurposeClinicalPracticeAsses" +
"sment\" data-bind=\"checked: PurposeClinicalPracticeAssessment\" />\r\n              " +
"      Clinical Practice Assessment\r\n                </label>\r\n            </li>\r" +
"\n            <li class=\"col3\">\r\n                <label for=\"chkPurposeEffectiven" +
"ess\">\r\n                    <input type=\"checkbox\" id=\"chkPurposeEffectiveness\" d" +
"ata-bind=\"checked: PurposeEffectiveness\" />\r\n                    Effectiveness\r\n" +
"                </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n    " +
"            <label for=\"chkPurposeNaturalHistoryofDisease\">\r\n                   " +
" <input type=\"checkbox\" id=\"chkPurposeNaturalHistoryofDisease\" data-bind=\"checke" +
"d: PurposeNaturalHistoryofDisease\" />\r\n                    Natural History of Di" +
"sease\r\n                </label>\r\n            </li>\r\n            <li class=\"col3\"" +
">\r\n                <label for=\"chkPurposePaymentCertification\">\r\n               " +
"     <input type=\"checkbox\" id=\"chkPurposePaymentCertification\" data-bind=\"check" +
"ed: PurposePaymentCertification\" />\r\n                    Payment/Certification\r\n" +
"                </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n    " +
"            <label for=\"chkPurposePostMarketingCommitment\">\r\n                   " +
" <input type=\"checkbox\" id=\"chkPurposePostMarketingCommitment\" data-bind=\"checke" +
"d: PurposePostMarketingCommitment\" />\r\n                    Post Marketing Commit" +
"ment\r\n                </label>\r\n            </li>\r\n            <li class=\"col3\">" +
"\r\n                <label for=\"chkPurposePublicHealthSurveillance\">\r\n            " +
"        <input type=\"checkbox\" id=\"chkPurposePublicHealthSurveillance\" data-bind" +
"=\"checked: PurposePublicHealthSurveillance\" />\r\n                    Public Healt" +
"h Surveillance\r\n                </label>\r\n            </li>\r\n            <li cla" +
"ss=\"col3\">\r\n                <label for=\"chkPurposeQualityImprovement\">\r\n        " +
"            <input type=\"checkbox\" id=\"chkPurposeQualityImprovement\" data-bind=\"" +
"checked: PurposeQualityImprovement\" />\r\n                    Quality Improvement\r" +
"\n                </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n   " +
"             <label for=\"chkPurposeSafetyOrHarm\">\r\n                    <input ty" +
"pe=\"checkbox\" id=\"chkPurposeSafetyOrHarm\" data-bind=\"checked: PurposeSafetyOrHar" +
"m\" />\r\n                    Safety Or Harm\r\n                </label>\r\n           " +
" </li>\r\n        </ol>\r\n        <br style=\"clear:both\" />\r\n        <ol>\r\n        " +
"    <li><span>Condition of Interest</span></li>\r\n            <li class=\"col3\">\r\n" +
"                <label for=\"chkConditionOfInterestBacterialandFungalDiseases\">\r\n" +
"                    <input type=\"checkbox\" id=\"chkConditionOfInterestBacterialan" +
"dFungalDiseases\" data-bind=\"checked: ConditionOfInterestBacterialandFungalDiseas" +
"es\" />\r\n                    Bacterial and Fungal Diseases\r\n                </lab" +
"el>\r\n            </li>\r\n            <li class=\"col3\">\r\n                <label fo" +
"r=\"chkConditionOfInterestBehaviorsandMentalDisorders\">\r\n                    <inp" +
"ut type=\"checkbox\" id=\"chkConditionOfInterestBehaviorsandMentalDisorders\" data-b" +
"ind=\"checked: ConditionOfInterestBehaviorsandMentalDisorders\" />\r\n              " +
"      Behaviors and Mental Disorders\r\n                </label>\r\n            </li" +
">\r\n            <li class=\"col3\">\r\n                <label for=\"chkConditionOfInte" +
"restBloodandLymphConditions\">\r\n                    <input type=\"checkbox\" id=\"ch" +
"kConditionOfInterestBloodandLymphConditions\" data-bind=\"checked: ConditionOfInte" +
"restBloodandLymphConditions\" />\r\n                    Blood and Lymph Conditions\r" +
"\n                </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n   " +
"             <label for=\"chkConditionOfInterestCancersAndOtherNeoplasms\">\r\n     " +
"               <input type=\"checkbox\" id=\"chkConditionOfInterestCancersAndOtherN" +
"eoplasms\" data-bind=\"checked: ConditionOfInterestCancersAndOtherNeoplasms\" />\r\n " +
"                   Cancers And Other Neoplasms\r\n                </label>\r\n      " +
"      </li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkCondi" +
"tionOfInterestDigestiveSystemDiseases\">\r\n                    <input type=\"checkb" +
"ox\" id=\"chkConditionOfInterestDigestiveSystemDiseases\" data-bind=\"checked: Condi" +
"tionOfInterestDigestiveSystemDiseases\" />\r\n                    Digestive System " +
"Diseases\r\n                </label>\r\n            </li>\r\n            <li class=\"co" +
"l3\">\r\n                <label for=\"chkConditionOfInterestDiseasesOrAbnormalitiesA" +
"tOrBeforeBirth\">\r\n                    <input type=\"checkbox\" id=\"chkConditionOfI" +
"nterestDiseasesOrAbnormalitiesAtOrBeforeBirth\" data-bind=\"checked: ConditionOfIn" +
"terestDiseasesOrAbnormalitiesAtOrBeforeBirth\" />\r\n                    Diseases O" +
"r Abnormalities At Or Before Birth\r\n                </label>\r\n            </li>\r" +
"\n            <li class=\"col3\">\r\n                <label for=\"chkConditionOfIntere" +
"stearNoseAndThroatDiseases\">\r\n                    <input type=\"checkbox\" id=\"chk" +
"ConditionOfInterestearNoseAndThroatDiseases\" data-bind=\"checked: ConditionOfInte" +
"restearNoseAndThroatDiseases\" />\r\n                    Ear, Nose, And Throat Dise" +
"ases\r\n                </label>\r\n            </li>\r\n            <li class=\"col3\">" +
"\r\n                <label for=\"chkConditionOfInterestEyeDiseases\">\r\n             " +
"       <input type=\"checkbox\" id=\"chkConditionOfInterestEyeDiseases\" data-bind=\"" +
"checked: ConditionOfInterestEyeDiseases\" />\r\n                    Eye Diseases\r\n " +
"               </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n     " +
"           <label for=\"chkConditionOfInterestGlandAndHormoneRelatedDiseases\">\r\n " +
"                   <input type=\"checkbox\" id=\"chkConditionOfInterestGlandAndHorm" +
"oneRelatedDiseases\" data-bind=\"checked: ConditionOfInterestGlandAndHormoneRelate" +
"dDiseases\" />\r\n                    Gland And Hormone Related Diseases\r\n         " +
"       </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n             " +
"   <label for=\"chkConditionOfInterestHeartAndBloodDiseases\">\r\n                  " +
"  <input type=\"checkbox\" id=\"chkConditionOfInterestHeartAndBloodDiseases\" data-b" +
"ind=\"checked: ConditionOfInterestHeartAndBloodDiseases\" />\r\n                    " +
"Heart And Blood Diseases\r\n                </label>\r\n            </li>\r\n         " +
"   <li class=\"col3\">\r\n                <label for=\"chkConditionOfInterestImmuneSy" +
"stemDiseases\">\r\n                    <input type=\"checkbox\" id=\"chkConditionOfInt" +
"erestImmuneSystemDiseases\" data-bind=\"checked: ConditionOfInterestImmuneSystemDi" +
"seases\" />\r\n                    Immune System Diseases\r\n                </label>" +
"\r\n            </li>\r\n            <li class=\"col3\">\r\n                <label for=\"" +
"chkConditionOfInterestMouthAndToothDiseases\">\r\n                    <input type=\"" +
"checkbox\" id=\"chkConditionOfInterestMouthAndToothDiseases\" data-bind=\"checked: C" +
"onditionOfInterestMouthAndToothDiseases\" />\r\n                    Mouth And Tooth" +
" Diseases\r\n                </label>\r\n            </li>\r\n            <li class=\"c" +
"ol3\">\r\n                <label for=\"chkConditionOfInterestNervousSystemDiseases\">" +
"\r\n                    <input type=\"checkbox\" id=\"chkConditionOfInterestNervousSy" +
"stemDiseases\" data-bind=\"checked: ConditionOfInterestNervousSystemDiseases\" />\r\n" +
"                    Nervous System Diseases\r\n                </label>\r\n         " +
"   </li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkConditio" +
"nOfInterestNutritionalAndMetabolicDiseases\">\r\n                    <input type=\"c" +
"heckbox\" id=\"chkConditionOfInterestNutritionalAndMetabolicDiseases\" data-bind=\"c" +
"hecked: ConditionOfInterestNutritionalAndMetabolicDiseases\" />\r\n                " +
"    Nutritional And Metabolic Diseases\r\n                </label>\r\n            </" +
"li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkConditionOfIn" +
"terestMuscleBoneCartilageDiseases\">\r\n                    <input type=\"checkbox\" " +
"id=\"chkConditionOfInterestMuscleBoneCartilageDiseases\" data-bind=\"checked: Condi" +
"tionOfInterestMuscleBoneCartilageDiseases\" />\r\n                    Muscle, Bone," +
" and Cartilage Diseases\r\n                </label>\r\n            </li>\r\n          " +
"  <li class=\"col3\">\r\n                <label for=\"chkConditionOfInterestOccupatio" +
"nalDiseases\">\r\n                    <input type=\"checkbox\" id=\"chkConditionOfInte" +
"restOccupationalDiseases\" data-bind=\"checked: ConditionOfInterestOccupationalDis" +
"eases\" />\r\n                    Occupational Diseases\r\n                </label>\r\n" +
"            </li>\r\n            <li class=\"col3\">\r\n                <label for=\"ch" +
"kConditionOfInterestParasiticalDiseases\">\r\n                    <input type=\"chec" +
"kbox\" id=\"chkConditionOfInterestParasiticalDiseases\" data-bind=\"checked: Conditi" +
"onOfInterestParasiticalDiseases\" />\r\n                    Parasitical Diseases\r\n " +
"               </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n     " +
"           <label for=\"chkConditionOfInterestRespiratoryTractDiseases\">\r\n       " +
"             <input type=\"checkbox\" id=\"chkConditionOfInterestRespiratoryTractDi" +
"seases\" data-bind=\"checked: ConditionOfInterestRespiratoryTractDiseases\" />\r\n   " +
"                 Respiratory Tract Diseases\r\n                </label>\r\n         " +
"   </li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkConditio" +
"nOfInterestSkinAndConnectiveTissueDiseases\">\r\n                    <input type=\"c" +
"heckbox\" id=\"chkConditionOfInterestSkinAndConnectiveTissueDiseases\" data-bind=\"c" +
"hecked: ConditionOfInterestSkinAndConnectiveTissueDiseases\" />\r\n                " +
"    Skin And Connective Tissue Diseases\r\n                </label>\r\n            <" +
"/li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkConditionOfI" +
"nterestSubstanceRelatedDisorders\">\r\n                    <input type=\"checkbox\" i" +
"d=\"chkConditionOfInterestSubstanceRelatedDisorders\" data-bind=\"checked: Conditio" +
"nOfInterestSubstanceRelatedDisorders\" />\r\n                    Substance Related " +
"Disorders\r\n                </label>\r\n            </li>\r\n            <li class=\"c" +
"ol3\">\r\n                <label for=\"chkConditionOfInterestSymptomsAndGeneralPatho" +
"logy\">\r\n                    <input type=\"checkbox\" id=\"chkConditionOfInterestSym" +
"ptomsAndGeneralPathology\" data-bind=\"checked: ConditionOfInterestSymptomsAndGene" +
"ralPathology\" />\r\n                    Symptoms And General Pathology\r\n          " +
"      </label>\r\n            </li>\r\n            <li class=\"col3\">\r\n              " +
"  <label for=\"chkConditionOfInterestUrinaryTractSexualOrgansAndPregnancyConditio" +
"ns\">\r\n                    <input type=\"checkbox\" id=\"chkConditionOfInterestUrina" +
"ryTractSexualOrgansAndPregnancyConditions\" data-bind=\"checked: ConditionOfIntere" +
"stUrinaryTractSexualOrgansAndPregnancyConditions\" />\r\n                    Urinar" +
"y Tract, SexualOrgans, And Pregnancy Conditions\r\n                </label>\r\n     " +
"       </li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkCond" +
"itionOfInterestViralDiseases\">\r\n                    <input type=\"checkbox\" id=\"c" +
"hkConditionOfInterestViralDiseases\" data-bind=\"checked: ConditionOfInterestViral" +
"Diseases\" />\r\n                    Viral Diseases\r\n                </label>\r\n    " +
"        </li>\r\n            <li class=\"col3\">\r\n                <label for=\"chkCon" +
"ditionOfInterestWoundsAndInjuries\">\r\n                    <input type=\"checkbox\" " +
"id=\"chkConditionOfInterestWoundsAndInjuries\" data-bind=\"checked: ConditionOfInte" +
"restWoundsAndInjuries\" />\r\n                    Wounds And Injuries\r\n            " +
"    </label>\r\n            </li>\r\n        </ol>\r\n\r\n    </fieldset>\r\n</div>\r\n\r\n<sc" +
"ript src=\"");


            
            #line 292 "..\..\Views\CreateRegSearch.cshtml"
        Write(this.Resource("CreateRegSearch.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script>\r\n    //Load the data here from the json that is serialized " +
"in from the model.\r\n    var data = JSON.parse(\'");


            
            #line 295 "..\..\Views\CreateRegSearch.cshtml"
                      Write(Html.Raw(Model.Data ?? "{}"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n    MetadataQuery.CreateRegistrySearch.init(data, $(\"#hData\"), $(\"#registryS" +
"earch\"));\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
