#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.General.Metadata.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns.General.CriteriaGroup;
    using Lpp.Dns.General.CriteriaGroup.Models;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    using Lpp.Utilities.Legacy;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CreateRegSearch.cshtml")]
    public partial class CreateRegSearch : System.Web.Mvc.WebViewPage<Lpp.Dns.General.Metadata.Models.MetadataRegSearchModel>
    {
        public CreateRegSearch()
        {
        }
        public override void Execute()
        {
WriteLiteral("<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hData\"");

WriteLiteral(" name=\"Data\"");

WriteLiteral(" /> <!--The entire model is stored in here as json-->\r\n<div");

WriteLiteral(" class=\"ui-groupbox\"");

WriteLiteral(" id=\"registrySearch\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui-groupbox-header\"");

WriteLiteral("><span>Search Criteria</span></div>\r\n\r\n    <fieldset");

WriteLiteral(" class=\"ui-groupbox\"");

WriteLiteral(">\r\n        <legend></legend>\r\n        <div");

WriteLiteral(" class=\"ui-groupbox-header\"");

WriteLiteral("><span>Registry Items</span></div>\r\n        <ol>\r\n            <li>\r\n             " +
"   <label");

WriteLiteral(" for=\"txtName\"");

WriteLiteral(">Name</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtName\"");

WriteLiteral(" data-bind=\"value: Name\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" />\r\n            </li>\r\n            <li><span>Classification</span></li>\r\n       " +
"     <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationDiseaseDisorderCondition\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationDiseaseDisorderCondition\"");

WriteLiteral(" data-bind=\"checked: ClassificationDiseaseDisorderCondition\"");

WriteLiteral(" />\r\n                    Disease/Disorder/Condition\r\n                </label>\r\n  " +
"          </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationRareDiseaseDisorderCondition\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkRareClassificationDiseaseDisorderCondition\"");

WriteLiteral(" data-bind=\"checked: ClassificationRareDiseaseDisorderCondition\"");

WriteLiteral(" />\r\n                    Rare Disease/Disorder/Condition\r\n                </label" +
">\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationPregnancy\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationPregnancy\"");

WriteLiteral(" data-bind=\"checked: ClassificationPregnancy\"");

WriteLiteral(" />\r\n                    Pregnancy\r\n                </label>\r\n            </li>\r\n" +
"            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationProductBiologic\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationProductBiologic\"");

WriteLiteral(" data-bind=\"checked: ClassificationProductBiologic\"");

WriteLiteral(" />\r\n                    Product,Biologic\r\n                </label>\r\n            " +
"</li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationProductDevice\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationProductDevice\"");

WriteLiteral(" data-bind=\"checked: ClassificationProductDevice\"");

WriteLiteral(" />\r\n                    Product,Device\r\n                </label>\r\n            </" +
"li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationProductDrug\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationProductDrug\"");

WriteLiteral(" data-bind=\"checked: ClassificationProductDrug\"");

WriteLiteral(" />\r\n                    Product,Drug\r\n                </label>\r\n            </li" +
">\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationServiceEncounter\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationServiceEncounter\"");

WriteLiteral(" data-bind=\"checked: ClassificationServiceEncounter\"");

WriteLiteral(" />\r\n                    Service,Encounter\r\n                </label>\r\n           " +
" </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationServiceHospitalization\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationServiceHospitalization\"");

WriteLiteral(" data-bind=\"checked: ClassificationServiceHospitalization\"");

WriteLiteral(" />\r\n                    Service,Hospitalization\r\n                </label>\r\n     " +
"       </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationServiceProcedure\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationServiceProcedure\"");

WriteLiteral(" data-bind=\"checked: ClassificationServiceProcedure\"");

WriteLiteral(" />\r\n                    Service,Procedure\r\n                </label>\r\n           " +
" </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationTransplant\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationTransplant\"");

WriteLiteral(" data-bind=\"checked: ClassificationTransplant\"");

WriteLiteral(" />\r\n                    Transplant\r\n                </label>\r\n            </li>\r" +
"\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationTumor\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationTumor\"");

WriteLiteral(" data-bind=\"checked: ClassificationTumor\"");

WriteLiteral(" />\r\n                    Tumor\r\n                </label>\r\n            </li>\r\n    " +
"        <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkClassificationVaccine\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkClassificationVaccine\"");

WriteLiteral(" data-bind=\"checked: ClassificationVaccine\"");

WriteLiteral(" />\r\n                    Vaccine\r\n                </label>\r\n            </li>\r\n  " +
"      </ol>\r\n        <br");

WriteLiteral(" style=\"clear:both\"");

WriteLiteral(" />\r\n        <ol>\r\n            <li><span>Purpose</span></li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkPurposeClinicalPracticeAssessment\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkPurposeClinicalPracticeAssessment\"");

WriteLiteral(" data-bind=\"checked: PurposeClinicalPracticeAssessment\"");

WriteLiteral(" />\r\n                    Clinical Practice Assessment\r\n                </label>\r\n" +
"            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkPurposeEffectiveness\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkPurposeEffectiveness\"");

WriteLiteral(" data-bind=\"checked: PurposeEffectiveness\"");

WriteLiteral(" />\r\n                    Effectiveness\r\n                </label>\r\n            </l" +
"i>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkPurposeNaturalHistoryofDisease\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkPurposeNaturalHistoryofDisease\"");

WriteLiteral(" data-bind=\"checked: PurposeNaturalHistoryofDisease\"");

WriteLiteral(" />\r\n                    Natural History of Disease\r\n                </label>\r\n  " +
"          </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkPurposePaymentCertification\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkPurposePaymentCertification\"");

WriteLiteral(" data-bind=\"checked: PurposePaymentCertification\"");

WriteLiteral(" />\r\n                    Payment/Certification\r\n                </label>\r\n       " +
"     </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkPurposePostMarketingCommitment\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkPurposePostMarketingCommitment\"");

WriteLiteral(" data-bind=\"checked: PurposePostMarketingCommitment\"");

WriteLiteral(" />\r\n                    Post Marketing Commitment\r\n                </label>\r\n   " +
"         </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkPurposePublicHealthSurveillance\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkPurposePublicHealthSurveillance\"");

WriteLiteral(" data-bind=\"checked: PurposePublicHealthSurveillance\"");

WriteLiteral(" />\r\n                    Public Health Surveillance\r\n                </label>\r\n  " +
"          </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkPurposeQualityImprovement\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkPurposeQualityImprovement\"");

WriteLiteral(" data-bind=\"checked: PurposeQualityImprovement\"");

WriteLiteral(" />\r\n                    Quality Improvement\r\n                </label>\r\n         " +
"   </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkPurposeSafetyOrHarm\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkPurposeSafetyOrHarm\"");

WriteLiteral(" data-bind=\"checked: PurposeSafetyOrHarm\"");

WriteLiteral(" />\r\n                    Safety Or Harm\r\n                </label>\r\n            </" +
"li>\r\n        </ol>\r\n        <br");

WriteLiteral(" style=\"clear:both\"");

WriteLiteral(" />\r\n        <ol>\r\n            <li><span>Condition of Interest</span></li>\r\n     " +
"       <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestBacterialandFungalDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestBacterialandFungalDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestBacterialandFungalDiseases\"");

WriteLiteral(" />\r\n                    Bacterial and Fungal Diseases\r\n                </label>\r" +
"\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestBehaviorsandMentalDisorders\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestBehaviorsandMentalDisorders\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestBehaviorsandMentalDisorders\"");

WriteLiteral(" />\r\n                    Behaviors and Mental Disorders\r\n                </label>" +
"\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestBloodandLymphConditions\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestBloodandLymphConditions\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestBloodandLymphConditions\"");

WriteLiteral(" />\r\n                    Blood and Lymph Conditions\r\n                </label>\r\n  " +
"          </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestCancersAndOtherNeoplasms\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestCancersAndOtherNeoplasms\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestCancersAndOtherNeoplasms\"");

WriteLiteral(" />\r\n                    Cancers And Other Neoplasms\r\n                </label>\r\n " +
"           </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestDigestiveSystemDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestDigestiveSystemDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestDigestiveSystemDiseases\"");

WriteLiteral(" />\r\n                    Digestive System Diseases\r\n                </label>\r\n   " +
"         </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestDiseasesOrAbnormalitiesAtOrBeforeBirth\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestDiseasesOrAbnormalitiesAtOrBeforeBirth\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestDiseasesOrAbnormalitiesAtOrBeforeBirth\"");

WriteLiteral(" />\r\n                    Diseases Or Abnormalities At Or Before Birth\r\n          " +
"      </label>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestearNoseAndThroatDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestearNoseAndThroatDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestearNoseAndThroatDiseases\"");

WriteLiteral(" />\r\n                    Ear, Nose, And Throat Diseases\r\n                </label>" +
"\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestEyeDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestEyeDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestEyeDiseases\"");

WriteLiteral(" />\r\n                    Eye Diseases\r\n                </label>\r\n            </li" +
">\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestGlandAndHormoneRelatedDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestGlandAndHormoneRelatedDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestGlandAndHormoneRelatedDiseases\"");

WriteLiteral(" />\r\n                    Gland And Hormone Related Diseases\r\n                </la" +
"bel>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestHeartAndBloodDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestHeartAndBloodDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestHeartAndBloodDiseases\"");

WriteLiteral(" />\r\n                    Heart And Blood Diseases\r\n                </label>\r\n    " +
"        </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestImmuneSystemDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestImmuneSystemDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestImmuneSystemDiseases\"");

WriteLiteral(" />\r\n                    Immune System Diseases\r\n                </label>\r\n      " +
"      </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestMouthAndToothDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestMouthAndToothDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestMouthAndToothDiseases\"");

WriteLiteral(" />\r\n                    Mouth And Tooth Diseases\r\n                </label>\r\n    " +
"        </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestNervousSystemDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestNervousSystemDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestNervousSystemDiseases\"");

WriteLiteral(" />\r\n                    Nervous System Diseases\r\n                </label>\r\n     " +
"       </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestNutritionalAndMetabolicDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestNutritionalAndMetabolicDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestNutritionalAndMetabolicDiseases\"");

WriteLiteral(" />\r\n                    Nutritional And Metabolic Diseases\r\n                </la" +
"bel>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestMuscleBoneCartilageDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestMuscleBoneCartilageDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestMuscleBoneCartilageDiseases\"");

WriteLiteral(" />\r\n                    Muscle, Bone, and Cartilage Diseases\r\n                </" +
"label>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestOccupationalDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestOccupationalDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestOccupationalDiseases\"");

WriteLiteral(" />\r\n                    Occupational Diseases\r\n                </label>\r\n       " +
"     </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestParasiticalDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestParasiticalDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestParasiticalDiseases\"");

WriteLiteral(" />\r\n                    Parasitical Diseases\r\n                </label>\r\n        " +
"    </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestRespiratoryTractDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestRespiratoryTractDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestRespiratoryTractDiseases\"");

WriteLiteral(" />\r\n                    Respiratory Tract Diseases\r\n                </label>\r\n  " +
"          </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestSkinAndConnectiveTissueDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestSkinAndConnectiveTissueDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestSkinAndConnectiveTissueDiseases\"");

WriteLiteral(" />\r\n                    Skin And Connective Tissue Diseases\r\n                </l" +
"abel>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestSubstanceRelatedDisorders\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestSubstanceRelatedDisorders\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestSubstanceRelatedDisorders\"");

WriteLiteral(" />\r\n                    Substance Related Disorders\r\n                </label>\r\n " +
"           </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestSymptomsAndGeneralPathology\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestSymptomsAndGeneralPathology\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestSymptomsAndGeneralPathology\"");

WriteLiteral(" />\r\n                    Symptoms And General Pathology\r\n                </label>" +
"\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestUrinaryTractSexualOrgansAndPregnancyConditions\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestUrinaryTractSexualOrgansAndPregnancyConditions\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestUrinaryTractSexualOrgansAndPregnancyCondi" +
"tions\"");

WriteLiteral(" />\r\n                    Urinary Tract, SexualOrgans, And Pregnancy Conditions\r\n " +
"               </label>\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestViralDiseases\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestViralDiseases\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestViralDiseases\"");

WriteLiteral(" />\r\n                    Viral Diseases\r\n                </label>\r\n            </" +
"li>\r\n            <li");

WriteLiteral(" class=\"col3\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"chkConditionOfInterestWoundsAndInjuries\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkConditionOfInterestWoundsAndInjuries\"");

WriteLiteral(" data-bind=\"checked: ConditionOfInterestWoundsAndInjuries\"");

WriteLiteral(" />\r\n                    Wounds And Injuries\r\n                </label>\r\n         " +
"   </li>\r\n        </ol>\r\n\r\n    </fieldset>\r\n</div>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 16068), Tuple.Create("\"", 16110)
            
            #line 292 "..\..\Views\CreateRegSearch.cshtml"
, Tuple.Create(Tuple.Create("", 16074), Tuple.Create<System.Object, System.Int32>(this.Resource("CreateRegSearch.js")
            
            #line default
            #line hidden
, 16074), false)
);

WriteLiteral("></script>\r\n<script>\r\n    //Load the data here from the json that is serialized i" +
"n from the model.\r\n    var data = JSON.parse(\'");

            
            #line 295 "..\..\Views\CreateRegSearch.cshtml"
                      Write(Html.Raw(Model.Data ?? "{}"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n    MetadataQuery.CreateRegistrySearch.init(data, $(\"#hData\"), $(\"#registryS" +
"earch\"));\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
