#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.General.Metadata.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns.General.CriteriaGroup;
    using Lpp.Dns.General.CriteriaGroup.Models;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    using Lpp.Utilities.Legacy;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DisplayOrgSearch.cshtml")]
    public partial class DisplayOrgSearch : System.Web.Mvc.WebViewPage<Lpp.Dns.General.Metadata.Models.MetadataOrgSearchModel>
    {
        public DisplayOrgSearch()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"ui-groupbox\"");

WriteLiteral(" id=\"orgSearch\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui-groupbox-header\"");

WriteLiteral("><span>Search Criteria</span></div>\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"hData\"");

WriteLiteral(" name=\"Data\"");

WriteLiteral(" /> <!--The entire model is stored in here as json-->\r\n    <fieldset>\r\n        <l" +
"egend>Organization Details</legend>\r\n        <ol>\r\n            <li>\r\n           " +
"     <label");

WriteLiteral(" for=\"txtName\"");

WriteLiteral(" data-bind=\"visible: Name() != null && Name() != \'\'\"");

WriteLiteral(">Name</label>\r\n                <span");

WriteLiteral(" style=\"font-weight: bold;\"");

WriteLiteral("  id=\"txtName\"");

WriteLiteral(" data-bind=\"value: Name\"");

WriteLiteral("></span>\r\n            </li>\r\n            <li>\r\n                <label");

WriteLiteral(" for=\"txtHealthPlanSystemDescription\"");

WriteLiteral(" data-bind=\"visible: HealthPlanSystemDescription() != null && HealthPlanSystemDes" +
"cription() != \'\'\"");

WriteLiteral(">Organization Description</label>\r\n                <span");

WriteLiteral(" style=\"font-weight: bold;\"");

WriteLiteral(" id=\"txtHealthPlanSystemDescription\"");

WriteLiteral(" data-bind=\"text: HealthPlanSystemDescription\"");

WriteLiteral(@"></span>
            </li>
            <!--keyword search on the new description field here-->
        </ol>
    </fieldset>


    <fieldset>
        <legend>Willing to Participate In:</legend>
        <ol>
            <li >
                <label");

WriteLiteral(" for=\"chkObservationalResearch\"");

WriteLiteral(" data-bind=\"visible: ObservationalResearch()\"");

WriteLiteral(">Observational Research</label>\r\n            </li>\r\n            <li >\r\n          " +
"      <label");

WriteLiteral(" for=\"chkClinicalTrials\"");

WriteLiteral(" data-bind=\"visible: ClinicalTrials()\"");

WriteLiteral(">Clinical Trials</label>\r\n            </li>\r\n            <li >\r\n                <" +
"label");

WriteLiteral(" for=\"chkPragamaticClincialTrials\"");

WriteLiteral(" data-bind=\"visible: PragamaticClincialTrials()\"");

WriteLiteral(@">Pragmatic Clinical Trials</label>
            </li>
        </ol>
    </fieldset>
    <fieldset>
        <legend></legend>
        <div><span>Types of Data Collected By Organization</span></div>
        <ol>
            <li >
                <label");

WriteLiteral(" for=\"chkNone\"");

WriteLiteral("data-bind=\"visible: None()\"");

WriteLiteral(">\r\n                    None\r\n                </label>\r\n            </li>\r\n       " +
"     <li >\r\n                <label");

WriteLiteral(" for=\"chkInpatient\"");

WriteLiteral(" data-bind=\"visible: Inpatient()\"");

WriteLiteral(">\r\n                    Inpatient\r\n                </label>\r\n            </li>\r\n  " +
"          <li >\r\n                <label");

WriteLiteral(" for=\"chkOutpatient\"");

WriteLiteral(" data-bind=\"visible: Outpatient()\"");

WriteLiteral(">\r\n                    Outpatient\r\n                </label>\r\n            </li>\r\n " +
"           <li >\r\n                <label");

WriteLiteral(" for=\"chkPharmacyDispensings\"");

WriteLiteral(" data-bind=\"visible: PharmacyDispensings()\"");

WriteLiteral(">\r\n                    Pharmacy Dispensings\r\n                </label>\r\n          " +
"  </li>\r\n            <li >\r\n                <label");

WriteLiteral(" for=\"chkEnrollment\"");

WriteLiteral(" data-bind=\"visible: Enrollment()\"");

WriteLiteral(">\r\n                    Enrollment\r\n                </label>\r\n            </li>\r\n " +
"           <li >\r\n                <label");

WriteLiteral(" for=\"chkDemographics\"");

WriteLiteral(" data-bind=\"visible: Demographics()\"");

WriteLiteral(">\r\n                    Demographics\r\n                </label>\r\n            </li>\r" +
"\n            <li >\r\n                <label");

WriteLiteral(" for=\"chkLaboratoryResults\"");

WriteLiteral(" data-bind=\"visible: LaboratoryResults()\"");

WriteLiteral(">\r\n                    Laboratory Results\r\n                </label>\r\n            " +
"</li>\r\n            <li >\r\n                <label");

WriteLiteral(" for=\"chkVitalSigns\"");

WriteLiteral(" data-bind=\"visible: VitalSigns()\"");

WriteLiteral(">\r\n                    Vital Signs\r\n                </label>\r\n            </li>\r\n" +
"            <li >\r\n                <label");

WriteLiteral(" for=\"chkBiorepositories\"");

WriteLiteral(" data-bind=\"visible: Biorepositories()\"");

WriteLiteral(">\r\n                    Biorepositories\r\n                </label>\r\n            </l" +
"i>\r\n            <li >\r\n                <label");

WriteLiteral(" for=\"chkPatientReportedOutcomes\"");

WriteLiteral(" data-bind=\"visible: PatientReportedOutcomes()\"");

WriteLiteral(">\r\n                    Patient Reported Outcomes/Health Status\r\n                <" +
"/label>\r\n            </li>\r\n            <li >\r\n                <label");

WriteLiteral(" for=\"chPatientReportedBehaviors\"");

WriteLiteral(" data-bind=\"visible: PatientReportedBehaviors()\"");

WriteLiteral(">\r\n                    Patient Reported Behaviors\r\n                </label>\r\n    " +
"        </li>\r\n            <li >\r\n                <label");

WriteLiteral(" for=\"chkPrescriptionOrders\"");

WriteLiteral(" data-bind=\"visible: PrescriptionOrders()\"");

WriteLiteral(">\r\n                    Prescription Orders\r\n                </label>\r\n           " +
" </li>\r\n            <li >\r\n                <label");

WriteLiteral(" for=\"chkOther\"");

WriteLiteral(" data-bind=\"visible: DataCollectedOther()\"");

WriteLiteral(@">
                    Other
                </label>
            </li>
        </ol>
    </fieldset>
    <fieldset>
        <legend></legend>
        <div><span>Electronic Health Record System</span></div>
        <div>Inpatient</div>
        <ol");

WriteLiteral(" style=\"width:46%; float:left;\"");

WriteLiteral(">            \r\n            <li >\r\n                <label");

WriteLiteral(" for=\"chkInpatientNone\"");

WriteLiteral(" data-bind=\"visible: InpatientNone()\"");

WriteLiteral(">\r\n                    None\r\n                </label>\r\n            </li>\r\n       " +
"     <li >\r\n                <label");

WriteLiteral(" for=\"chkInpatientEpic\"");

WriteLiteral(" data-bind=\"visible: InpatientEpic()\"");

WriteLiteral(">\r\n                    Epic\r\n                </label>\r\n            </li>\r\n       " +
"     <li >\r\n                <label");

WriteLiteral(" for=\"chkInpatientNextGenHealthCare\"");

WriteLiteral(" data-bind=\"visible: InpatientNextGenHealthCare()\"");

WriteLiteral(">\r\n                    NextGen HealthCare\r\n                </label>\r\n            " +
"</li>\r\n            <li >\r\n                <label");

WriteLiteral(" for=\"chkInpatientGEHealthCare\"");

WriteLiteral(" data-bind=\"visible: InpatientGEHealthcare()\"");

WriteLiteral(">\r\n                    GE HealthCare\r\n                </label>\r\n            </li>" +
"\r\n            <li >\r\n                <label");

WriteLiteral(" id=\"chkInpatientAllScripts\"");

WriteLiteral(" data-bind=\"visible: InpatientAllScripts()\"");

WriteLiteral(">\r\n                    AllScripts\r\n                </label>\r\n            </li>\r\n " +
"           <li >\r\n                <label");

WriteLiteral(" id=\"chkInpatientClinicalWorks\"");

WriteLiteral(" data-bind=\"visible: InpatienteClinicalWorks()\"");

WriteLiteral(">\r\n                    eClinicalWorks\r\n                </label>\r\n            </li" +
">\r\n            <li >\r\n                <label");

WriteLiteral(" id=\"chkInpatientMckesson\"");

WriteLiteral(" data-bind=\"visible: InpatientMckesson()\"");

WriteLiteral(">\r\n                    Mckesson\r\n                </label>\r\n            </li>\r\n   " +
"         <li >\r\n                <label");

WriteLiteral(" id=\"chkInpatientCare360\"");

WriteLiteral(" data-bind=\"visible: InpatientCare360()\"");

WriteLiteral(">\r\n                    Care 360\r\n                </label>\r\n            </li>\r\n   " +
"         <li >\r\n                <label");

WriteLiteral(" id=\"chkInpatientMeditech\"");

WriteLiteral(" data-bind=\"visible: InpatientMeditech()\"");

WriteLiteral(">\r\n                    Meditech\r\n                </label>\r\n            </li>\r\n   " +
"         \r\n            <li >\r\n                <label");

WriteLiteral(" id=\"chkInpatientCPSI\"");

WriteLiteral(" data-bind=\"visible: InpatientCPSI()\"");

WriteLiteral(" >\r\n                    CPSI\r\n                </label>\r\n            </li>\r\n      " +
"      <li >\r\n                <label");

WriteLiteral(" id=\"chkInpatientCerner\"");

WriteLiteral(" data-bind=\"visible: InpatientCerner()\"");

WriteLiteral(" >\r\n                    Cerner\r\n                </label>\r\n            </li>\r\n    " +
"        <li>\r\n                <label");

WriteLiteral(" id=\"chkInpatientOther\"");

WriteLiteral(" data-bind=\"visible: InpatientOther()\"");

WriteLiteral(">\r\n                    Other\r\n                </label>\r\n            </li>\r\n      " +
"  </ol>\r\n        <div>Outpatient</div>\r\n        <ol");

WriteLiteral(" style=\"width:46%; float:left; padding-left:20px;\"");

WriteLiteral(">\r\n            \r\n            <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientNone\"");

WriteLiteral(" data-bind=\"visible: OutpatientNone()\"");

WriteLiteral(">\r\n                    None\r\n                </label>\r\n            </li>\r\n       " +
"     <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientEpic\"");

WriteLiteral(" data-bind=\"visible: OutpatientEpic()\"");

WriteLiteral(">\r\n                    Epic\r\n                </label>\r\n            </li>\r\n       " +
"     <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientNextGenHealthCare\"");

WriteLiteral(" data-bind=\"visible: OutpatientNextGenHealthCare()\"");

WriteLiteral(">\r\n                    NextGen HealthCare\r\n                </label>\r\n            " +
"</li>\r\n            <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientGEHealthCare\"");

WriteLiteral(" data-bind=\"visible: OutpatientGEHealthcare()\"");

WriteLiteral(">\r\n                    GE HealthCare\r\n                </label>\r\n            </li>" +
"\r\n            <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientAllScripts\"");

WriteLiteral(" data-bind=\"visible: OutpatientAllScripts()\"");

WriteLiteral(">\r\n                    AllScripts\r\n                </label>\r\n            </li>\r\n " +
"           <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientClinicalWorks\"");

WriteLiteral(" data-bind=\"visible: OutpatienteClinicalWorks()\"");

WriteLiteral(">\r\n                    eClinicalWorks\r\n                </label>\r\n            </li" +
">\r\n            <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientMckesson\"");

WriteLiteral(" data-bind=\"visible: OutpatientMckesson()\"");

WriteLiteral(">\r\n                    Mckesson\r\n                </label>\r\n            </li>\r\n   " +
"         <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientCare360\"");

WriteLiteral(" data-bind=\"visible: OutpatientCare360()\"");

WriteLiteral(">\r\n                    Care 360\r\n                </label>\r\n            </li>\r\n   " +
"         <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientMeditech\"");

WriteLiteral(" data-bind=\"visible: OutpatientMeditech()\"");

WriteLiteral(">\r\n                    Meditech\r\n                </label>\r\n            </li>\r\n   " +
"         \r\n            <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientCerner\"");

WriteLiteral(" data-bind=\"visible: OutpatientCerner()\"");

WriteLiteral(">\r\n                    Cerner\r\n                </label>\r\n            </li>\r\n     " +
"       <li >\r\n                <label");

WriteLiteral(" id=\"chkOutpatientCPSI\"");

WriteLiteral(" data-bind=\"visible: OutpatientCPSI()\"");

WriteLiteral(">\r\n                    CPSI\r\n                </label>\r\n            </li>\r\n       " +
"     <li>\r\n                <label");

WriteLiteral(" id=\"chkOutpatientOther\"");

WriteLiteral(" data-bind=\"visible: OutpatientOther()\"");

WriteLiteral(">\r\n                    Other\r\n                </label>\r\n            </li>\r\n      " +
"  </ol>\r\n    </fieldset>\r\n    <fieldset>\r\n        <legend></legend>\r\n        <di" +
"v><span>Data Models</span></div>\r\n        <ol>\r\n            <li >\r\n             " +
"   <label");

WriteLiteral(" id=\"chkDataModelMSCDM\"");

WriteLiteral(" data-bind=\"visible: DataModelMSCDM()\"");

WriteLiteral(">\r\n                    MSCDM\r\n                </label>\r\n            </li>\r\n      " +
"      <li >\r\n                <label");

WriteLiteral(" id=\"chkDataModelESP\"");

WriteLiteral(" data-bind=\"visible: DataModelESP()\"");

WriteLiteral(">\r\n                    ESP\r\n                </label>\r\n            </li>\r\n        " +
"    <li >\r\n                <label");

WriteLiteral(" id=\"chkDataModelOMOP\"");

WriteLiteral(" data-bind=\"visible: DataModelOMOP()\"");

WriteLiteral(">\r\n                    OMOP\r\n                </label>\r\n            </li>\r\n       " +
"     <li >\r\n                <label");

WriteLiteral(" id=\"chkDataModelHMRON\"");

WriteLiteral(" data-bind=\"visible: DataModelHMRON()\"");

WriteLiteral(">\r\n                    HMORN VDW\r\n                </label>\r\n            </li>\r\n  " +
"          <li >\r\n                <label");

WriteLiteral(" id=\"chkDataModeli2b2\"");

WriteLiteral(" data-bind=\"visible: DataModeli2b2()\"");

WriteLiteral(">\r\n                    i2b2\r\n                </label>\r\n            </li>\r\n       " +
"     <li>\r\n                <label");

WriteLiteral(" id=\"chkDataModelPcori\"");

WriteLiteral(" data-bind=\"visible: DataModelPCORI()\"");

WriteLiteral(">\r\n                    PCORnet CDM\r\n                </label>\r\n            </li>\r\n" +
"            <li >\r\n                <label");

WriteLiteral(" data-bind=\"visible: DataModelOther()\"");

WriteLiteral(@">
                    Other
                </label>
            </li>
        </ol>
    </fieldset>


    <!--More field sets for each area per the screen shot-->
    <!--update the CreateOrgSearch.ts to have the new knockout and update the IOrgSerach interface to have the value, in the constructor set the observable and in the save set the interface data for the new field.
        In the models/MetadataOrgSearchModel update the data class to have the new field of the valid format. You're done.-->
</div>

<script");

WriteAttribute("src", Tuple.Create(" src=\"", 10949), Tuple.Create("\"", 11019)
            
            #line 287 "..\..\Views\DisplayOrgSearch.cshtml"
, Tuple.Create(Tuple.Create("", 10955), Tuple.Create<System.Object, System.Int32>(Lpp.Mvc.ResourceExtensions.Resource(this, "CreateOrgSearch.js")
            
            #line default
            #line hidden
, 10955), false)
);

WriteLiteral("></script>\r\n<script>\r\n    //Load the data here from the json that is serialized i" +
"n from the model.\r\n    //Reuses the code from the edit and just changes the bind" +
"ings\r\n    var data = JSON.parse(\'");

            
            #line 291 "..\..\Views\DisplayOrgSearch.cshtml"
                      Write(Html.Raw(Model.Data ?? "{}"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n    MetadataQuery.CreateOrgSearch.init(data, $(\"#hData\"), $(\"#orgSearch\"));\r" +
"\n</script>");

        }
    }
}
#pragma warning restore 1591
