#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lpp.Dns.Portal.Views.Crud
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Lpp;
    using Lpp.Dns;
    using Lpp.Dns.Data;
    using Lpp.Dns.Portal;
    using Lpp.Dns.Portal.Controllers;
    using Lpp.Dns.Portal.Models;
    using Lpp.Dns.Portal.Views;
    using Lpp.Mvc;
    using Lpp.Mvc.Application;
    using Lpp.Mvc.Controls;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Crud/ObjectSelector.cshtml")]
    public partial class ObjectSelector : System.Web.Mvc.WebViewPage<ObjectSelectorModel>
    {
        public ObjectSelector()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Crud\ObjectSelector.cshtml"
  
    Layout = null; 
    var id = Html.UniqueId();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"Value ObjectSelector\"");

WriteAttribute("id", Tuple.Create(" id=\"", 122), Tuple.Create("\"", 130)
            
            #line 7 "..\..\Views\Crud\ObjectSelector.cshtml"
, Tuple.Create(Tuple.Create("", 127), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 127), false)
);

WriteLiteral(">\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"Link\"");

WriteLiteral(">");

            
            #line 8 "..\..\Views\Crud\ObjectSelector.cshtml"
                         Write(Model.CurrentValue == null ? "<none>" : Model.CurrentValue.Value.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 9 "..\..\Views\Crud\ObjectSelector.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Crud\ObjectSelector.cshtml"
     if ( Model.AllowClear )
    {
            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"Clear\"");

WriteLiteral(">[x]</a> ");

            
            #line 10 "..\..\Views\Crud\ObjectSelector.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 338), Tuple.Create("\"", 361)
            
            #line 11 "..\..\Views\Crud\ObjectSelector.cshtml"
, Tuple.Create(Tuple.Create("", 345), Tuple.Create<System.Object, System.Int32>(Model.FieldName
            
            #line default
            #line hidden
, 345), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 362), Tuple.Create("\"", 434)
            
            #line 11 "..\..\Views\Crud\ObjectSelector.cshtml"
, Tuple.Create(Tuple.Create("", 370), Tuple.Create<System.Object, System.Int32>(Model.CurrentValue == null ? "" : Model.CurrentValue.Value.ID
            
            #line default
            #line hidden
, 370), false)
);

WriteLiteral(" />\r\n    <div");

WriteLiteral(" class=\"Options\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n        <h3>TODO: fix grid</h3>\r\n        ");

WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 644), Tuple.Create("\"", 685)
            
            #line 18 "..\..\Views\Crud\ObjectSelector.cshtml"
, Tuple.Create(Tuple.Create("", 650), Tuple.Create<System.Object, System.Int32>(this.Resource("ObjectSelector.js")
            
            #line default
            #line hidden
, 650), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(function () {\r\n        $(\"#");

            
            #line 21 "..\..\Views\Crud\ObjectSelector.cshtml"
        Write(id);

            
            #line default
            #line hidden
WriteLiteral("\").objectSelector( \'");

            
            #line 21 "..\..\Views\Crud\ObjectSelector.cshtml"
                                Write(Html.Raw((Model.DialogTitle ?? "").Replace("'", "\\'")));

            
            #line default
            #line hidden
WriteLiteral("\' );\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
